# Generated by Django 6.0.3 on 2026-09-06 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('decidir', 'Decidir'), ('em_andamento', 'Já sendo feito'), ('aguardando', 'Aguardando terceiros'), ('concluido', 'Concluídos'), ('adiado', 'Adiados')], db_index=True, default='decidir', max_length=20)),
                ('loja', models.CharField(choices=[('geral', 'Geral'), ('centro', 'Centro'), ('vila', 'Vila Elias'), ('ambas', 'Centro e Vila')], default='geral', max_length=16)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('seed_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('criado_por_nome', models.CharField(blank=True, default='', max_length=150)),
                ('atualizado_por_nome', models.CharField(blank=True, default='', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarefa / pendência',
                'verbose_name_plural': 'Tarefas / pendências',
                'ordering': ['ordem', '-atualizado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TarefaComentarioAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor_nome', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tarefas.tarefaagro')),
            ],
            options={
                'verbose_name': 'Comentário de tarefa',
                'verbose_name_plural': 'Comentários de tarefa',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaEventoAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criada', 'Criada'), ('editada', 'Editada'), ('status', 'Mudança de status'), ('comentario', 'Comentário'), ('concluida', 'Concluída')], max_length=20)),
                ('autor_nome', models.CharField(max_length=150)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tarefas.tarefaagro')),
            ],
            options={
                'verbose_name': 'Evento de tarefa',
                'verbose_name_plural': 'Eventos de tarefa',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
