# Generated by Django 6.0.3 on 2026-09-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_seed_agro_mais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaagro',
            name='status',
            field=models.CharField(choices=[('decidir', 'Decidir'), ('em_andamento', 'Já sendo feito'), ('aguardando', 'Aguardando terceiros'), ('concluido', 'Concluídos'), ('adiado', 'Adiados'), ('adiado_permanente', 'Adiado permanente'), ('cancelado', 'Cancelados')], db_index=True, default='decidir', max_length=24),
        ),
    ]
