# Generated by Django 6.0.3 on 2026-03-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteRapidoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=100)),
                ('codigo_interno', models.CharField(blank=True, default='', max_length=100)),
                ('nome_produto', models.CharField(blank=True, default='', max_length=255)),
                ('deposito', models.CharField(choices=[('centro', 'Centro'), ('vila', 'Vila Elias')], db_index=True, max_length=20)),
                ('saldo_erp_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('saldo_ajustado', models.DecimalField(decimal_places=3, max_digits=12)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajuste Rápido de Estoque',
                'verbose_name_plural': 'Ajustes Rápidos de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
