# Generated by Django 6.0.3 on 2026-03-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_ajusterapidoestoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajusterapidoestoque',
            old_name='saldo_erp_anterior',
            new_name='diferenca_saldo',
        ),
        migrations.RemoveField(
            model_name='ajusterapidoestoque',
            name='saldo_ajustado',
        ),
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='saldo_erp_referencia',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='saldo_informado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
