# Generated by Django 6.0.3 on 2026-03-18 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('estoque', '0003_rename_saldo_erp_anterior_ajusterapidoestoque_diferenca_saldo_and_more'),
        ('produtos', '0002_produto_empresa_alter_produto_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_rapidos_estoque', to='base.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='base.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='base.loja'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('produto', 'loja'), name='unique_produto_loja_estoque'),
        ),
    ]
