# Generated by Django 6.0.3 on 2026-03-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('estoque', '0004_alter_estoque_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_rapidos', to='base.loja', verbose_name='Loja'),
        ),
    ]
