# Generated by Django 6.0.3 on 2026-03-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('estoque', '0005_ajusterapidoestoque_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajusterapidoestoque',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='ajusterapidoestoque',
            name='deposito',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ajusterapidoestoque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.empresa'),
        ),
        migrations.AlterField(
            model_name='ajusterapidoestoque',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.loja'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='base.empresa'),
        ),
    ]
