# Generated by Django 6.0.3 on 2026-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_ajusterapidoestoque_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=100, unique=True)),
                ('estoque_seguranca', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('estoque_maximo_centro', models.DecimalField(decimal_places=3, default=15, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ajusterapidoestoque',
            options={'ordering': ['-criado_em']},
        ),
    ]
