# Generated by Django 6.0.3 on 2026-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_configuracaoproduto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID do Produto')),
                ('nome_produto', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Produto')),
                ('venda_media_diaria', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Venda Média Diária')),
                ('capacidade_maxima', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Capacidade Máxima')),
                ('dias_cobertura', models.IntegerField(default=1, verbose_name='Dias de Cobertura')),
                ('estoque_seguranca', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque Segurança')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Transferência',
                'verbose_name_plural': 'Configurações de Transferências',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoProduto',
        ),
    ]
