# Generated by Django 6.0.3 on 2026-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_configuracaotransferencia_delete_configuracaoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
