# Generated by Django 6.0.3 on 2026-04-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_integracao_pedido_labels'),
        ('estoque', '0009_pedidotransferencia'),
        ('produtos', '0009_opcao_baixa_financeiro_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_base', models.DateField(db_index=True)),
                ('saldo_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('venda_media_dia', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('dias_sem_venda', models.IntegerField(default=9999)),
                ('dias_cobertura_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('necessidade', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('preco_venda', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('margem_bruta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('score_prioridade', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('classe_abc', models.CharField(blank=True, default='', max_length=1)),
                ('classe_criticidade', models.CharField(blank=True, default='', max_length=20)),
                ('sugestao_acao', models.CharField(blank=True, default='', max_length=30)),
                ('qtd_transferir', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qtd_comprar', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loja')),
                ('loja_origem_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores_como_origem_sugerida', to='base.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'db_table': 'indicador_produto_loja',
                'indexes': [models.Index(fields=['empresa', 'loja', 'data_base'], name='indicador_p_empresa_a935d3_idx'), models.Index(fields=['empresa', 'loja', 'score_prioridade'], name='indicador_p_empresa_2721be_idx'), models.Index(fields=['empresa', 'loja', 'classe_abc', 'score_prioridade'], name='indicador_p_empresa_803310_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'loja', 'produto', 'data_base'), name='uniq_indicador_emp_loja_prod_data')],
            },
        ),
        migrations.CreateModel(
            name='PoliticaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_seguranca', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('dias_cobertura', models.DecimalField(decimal_places=2, default=15, max_digits=8)),
                ('capacidade_maxima', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estoque_minimo_manual', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estoque_ideal_manual', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('permite_transferencia', models.BooleanField(default=True)),
                ('permite_compra', models.BooleanField(default=True)),
                ('prioridade_manual', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'db_table': 'politica_estoque',
                'indexes': [models.Index(fields=['empresa', 'loja', 'produto'], name='politica_es_empresa_7a29dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'loja', 'produto'), name='uniq_politica_estoque_emp_loja_prod')],
            },
        ),
    ]
