# Generated by Django 6.0.3 on 2026-04-07 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_indicadorprodutoloja_politicaestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueSyncHealth',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mongo_ultimo_ping_em', models.DateTimeField(blank=True, null=True)),
                ('mongo_ultimo_ok', models.BooleanField(default=True)),
                ('mongo_ultimo_erro', models.TextField(blank=True)),
                ('catalogo_ultimo_build_em', models.DateTimeField(blank=True, null=True)),
                ('catalogo_ultima_versao', models.CharField(blank=True, max_length=80)),
                ('falhas_sequenciais_mongo', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saúde sync estoque (Agro)',
                'verbose_name_plural': 'Saúde sync estoque (Agro)',
            },
        ),
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='origem',
            field=models.CharField(choices=[('ajuste_pin', 'Ajuste PIN / modal'), ('entrada_nf_agro', 'Entrada NF (Agro)'), ('baixa_venda_pdv', 'Baixa venda PDV'), ('transferencia_ui', 'Transferência / tela'), ('planilha', 'Importação planilha'), ('outro', 'Outro')], db_index=True, default='outro', max_length=40),
        ),
        migrations.AddField(
            model_name='ajusterapidoestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_estoque_agro', to=settings.AUTH_USER_MODEL),
        ),
    ]
