# Generated by Django 6.0.3 on 2026-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_historicotransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusterapidoestoque',
            name='origem',
            field=models.CharField(choices=[('ajuste_pin', 'Ajuste PIN / modal'), ('entrada_nf_agro', 'Entrada NF (Agro)'), ('baixa_venda_pdv', 'Baixa venda PDV'), ('devolucao_venda_pdv', 'Devolução venda PDV'), ('transferencia_ui', 'Transferência / tela'), ('planilha', 'Importação planilha'), ('vencimento_em_loja', 'Vencimento em Loja'), ('uso_loja', 'Uso loja'), ('estorno_uso_loja', 'Estorno uso loja'), ('outro', 'Outro')], db_index=True, default='outro', max_length=40),
        ),
    ]
