# Generated by Django 6.0.3 on 2026-08-13 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_estorno_entrada_nf_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusterapidoestoque',
            name='origem',
            field=models.CharField(choices=[('ajuste_pin', 'Ajuste PIN / modal'), ('entrada_nf_agro', 'Entrada NF (Agro)'), ('estorno_entrada_nf_agro', 'Estorno entrada NF (reabrir)'), ('baixa_venda_pdv', 'Baixa venda PDV'), ('devolucao_venda_pdv', 'Devolução venda PDV'), ('transferencia_ui', 'Transferência / tela'), ('planilha', 'Importação planilha'), ('vencimento_em_loja', 'Vencimento em Loja'), ('uso_loja', 'Uso loja'), ('estorno_uso_loja', 'Estorno uso loja'), ('contagem_ciclica', 'Contagem cíclica'), ('outro', 'Outro')], db_index=True, default='outro', max_length=40),
        ),
        migrations.CreateModel(
            name='ContagemCiclicaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(db_index=True, max_length=20)),
                ('escopo_tipo', models.CharField(choices=[('loja', 'Loja inteira'), ('categoria', 'Categoria'), ('corredor', 'Corredor')], db_index=True, max_length=20)),
                ('escopo_valor', models.CharField(blank=True, default='', help_text='Categoria ou nome do corredor (vazio se loja inteira).', max_length=200)),
                ('status', models.CharField(choices=[('pass1', 'Passagem 1'), ('pass2', 'Recontagem'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], db_index=True, default='pass1', max_length=20)),
                ('passagem_atual', models.PositiveSmallIntegerField(default=1)),
                ('total_itens', models.PositiveIntegerField(default=0)),
                ('contados_pass1', models.PositiveIntegerField(default=0)),
                ('contados_pass2', models.PositiveIntegerField(default=0)),
                ('aberta_por_rotulo', models.CharField(blank=True, default='', max_length=120)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('pass1_fechada_em', models.DateTimeField(blank=True, null=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('aberta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_ciclicas_abertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='ContagemCiclicaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_rotulo', models.CharField(max_length=120)),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_ping_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_ciclicas_participacoes', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='estoque.contagemciclicasessao')),
            ],
            options={
                'ordering': ['operador_rotulo'],
            },
        ),
        migrations.CreateModel(
            name='ContagemCiclicaLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=100)),
                ('codigo_interno', models.CharField(blank=True, default='', max_length=100)),
                ('nome_produto', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(blank=True, default='', max_length=200)),
                ('saldo_referencia', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('custo_ref', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qtd_pass1', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('qtd_pass2', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('qtd_final', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('contado_pass1', models.BooleanField(db_index=True, default=False)),
                ('contado_pass2', models.BooleanField(db_index=True, default=False)),
                ('precisa_recontagem', models.BooleanField(db_index=True, default=False)),
                ('auto_zero_pass1', models.BooleanField(default=False)),
                ('operador_pass1', models.CharField(blank=True, default='', max_length=120)),
                ('operador_pass2', models.CharField(blank=True, default='', max_length=120)),
                ('contado_pass1_em', models.DateTimeField(blank=True, null=True)),
                ('contado_pass2_em', models.DateTimeField(blank=True, null=True)),
                ('ajuste_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='estoque.contagemciclicasessao')),
            ],
            options={
                'ordering': ['nome_produto', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='contagemciclicasessao',
            index=models.Index(fields=['deposito', 'status'], name='estoque_con_deposit_a2a9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='contagemciclicasessao',
            index=models.Index(fields=['deposito', 'escopo_tipo', 'escopo_valor', 'status'], name='estoque_con_deposit_00f1fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='contagemciclicaparticipante',
            constraint=models.UniqueConstraint(fields=('sessao', 'operador_rotulo'), name='uniq_ciclica_sessao_operador'),
        ),
        migrations.AddIndex(
            model_name='contagemciclicalinha',
            index=models.Index(fields=['sessao', 'contado_pass1'], name='estoque_con_sessao__818324_idx'),
        ),
        migrations.AddIndex(
            model_name='contagemciclicalinha',
            index=models.Index(fields=['sessao', 'precisa_recontagem'], name='estoque_con_sessao__cda13e_idx'),
        ),
        migrations.AddConstraint(
            model_name='contagemciclicalinha',
            constraint=models.UniqueConstraint(fields=('sessao', 'produto_externo_id'), name='uniq_ciclica_sessao_produto'),
        ),
    ]
