# Generated by Django 6.0.3 on 2026-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_contagem_ciclica'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagemciclicasessao',
            name='dias_movimentacao',
            field=models.PositiveIntegerField(default=60, help_text='Só produtos com movimento Agro no depósito nos últimos N dias. 0 = sem filtro.'),
        ),
    ]
