# Generated by Django 6.0.3 on 2026-08-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_solicitacao_transferencia_pdv'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitacaotransferenciapdv',
            new_name='estoque_sol_loja_or_d79150_idx',
            old_name='estoque_sol_loja_or_8c1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacaotransferenciapdv',
            new_name='estoque_sol_loja_de_ac7b6f_idx',
            old_name='estoque_sol_loja_de_9d2c3a_idx',
        ),
    ]
