# Generated by Django 6.0.3 on 2026-04-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_alter_integracaoerp_pedido_plano_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apelido', models.CharField(blank=True, max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='base.empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='base.loja')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['empresa_id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoFolhaSimplificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Primeiro dia do mês (ex.: 2025-04-01).')),
                ('salario_base_na_competencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_vales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outros_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outros_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_liquido_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('PAGO_PARCIAL', 'Pago parcial'), ('PAGO', 'Pago')], default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_folha', to='base.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Fechamento de folha (simplificado)',
                'verbose_name_plural': 'Fechamentos de folha',
                'ordering': ['-competencia', 'funcionario__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField(blank=True, null=True)),
                ('motivo_alteracao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_salario', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Histórico salarial',
                'verbose_name_plural': 'Históricos salariais',
                'ordering': ['-data_inicio_vigencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InconsistenciaIntegracaoRh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VALE_SEM_FUNCIONARIO', 'Vale (caixa) sem funcionário'), ('FUNCIONARIO_INATIVO', 'Funcionário inativo'), ('DIVERGENCIA', 'Divergência com lançamento'), ('LANCAMENTO_REMOVIDO', 'Lançamento removido no financeiro')], max_length=40)),
                ('referencia_externa_tipo', models.CharField(blank=True, max_length=80)),
                ('referencia_externa_id', models.CharField(blank=True, max_length=64)),
                ('detalhe', models.TextField(blank=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_inconsistencias', to='base.empresa')),
            ],
            options={
                'verbose_name': 'Inconsistência (integração RH)',
                'verbose_name_plural': 'Inconsistências (integração RH)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemFechamentoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALARIO_BASE', 'Salário base'), ('VALE', 'Vale'), ('DESCONTO', 'Desconto'), ('ACRESCIMO', 'Acréscimo'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('descricao', models.CharField(max_length=400)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_tipo', models.CharField(blank=True, max_length=80)),
                ('referencia_id', models.CharField(blank=True, max_length=64)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rh.fechamentofolhasimplificado')),
            ],
            options={
                'verbose_name': 'Item de fechamento',
                'verbose_name_plural': 'Itens de fechamento',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValeFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_origem', models.CharField(choices=[('MANUAL', 'Manual'), ('CAIXAS', 'Caixas')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('referencia_externa_tipo', models.CharField(blank=True, max_length=80)),
                ('referencia_externa_id', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=400)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_rh_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_funcionario', to='base.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='rh.funcionario')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_funcionario', to='base.loja')),
            ],
            options={
                'verbose_name': 'Vale / adiantamento',
                'verbose_name_plural': 'Vales / adiantamentos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['empresa', 'ativo', 'nome'], name='rh_funciona_empresa_d603e8_idx'),
        ),
        migrations.AddIndex(
            model_name='fechamentofolhasimplificado',
            index=models.Index(fields=['empresa', 'competencia', 'status'], name='rh_fechamen_empresa_5c3791_idx'),
        ),
        migrations.AddConstraint(
            model_name='fechamentofolhasimplificado',
            constraint=models.UniqueConstraint(fields=('funcionario', 'competencia'), name='rh_fechamento_unico_func_comp'),
        ),
        migrations.AddIndex(
            model_name='valefuncionario',
            index=models.Index(fields=['empresa', 'data'], name='rh_valefunc_empresa_7beb03_idx'),
        ),
        migrations.AddIndex(
            model_name='valefuncionario',
            index=models.Index(fields=['funcionario', 'data'], name='rh_valefunc_funcion_e9f8ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='valefuncionario',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_externa_id__gt', '')), fields=('referencia_externa_tipo', 'referencia_externa_id'), name='rh_vale_unico_ref_externa'),
        ),
    ]
