# Generated by Django 6.0.3 on 2026-04-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_fechamento_titulo_salario_mongo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='funcionario',
            new_name='rh_funciona_empresa_c3d5b0_idx',
            old_name='rh_funciona_empresa_nomec_idx',
        ),
        migrations.AlterField(
            model_name='fechamentofolhasimplificado',
            name='data_vencimento_pagamento',
            field=models.DateField(blank=True, help_text='Vencimento do título de salário no financeiro (Mongo).', null=True),
        ),
    ]
