# Generated by Django 6.0.3 on 2026-07-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_limpar_plano_pedido_erp_sisvale'),
        ('rh', '0004_rename_rh_funciona_empresa_nomec_idx_rh_funciona_empresa_c3d5b0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfechamentofolha',
            name='tipo',
            field=models.CharField(choices=[('SALARIO_BASE', 'Salário base'), ('VALE', 'Vale'), ('PAGAMENTO_SALARIO', 'Pagamento salário'), ('DESCONTO', 'Desconto'), ('ACRESCIMO', 'Acréscimo'), ('AJUSTE', 'Ajuste')], max_length=20),
        ),
        migrations.CreateModel(
            name='PagamentoSalarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_origem', models.CharField(choices=[('CP_TOTAL', 'Contas a pagar (quitação)'), ('CP_PARCIAL', 'Contas a pagar (parcial)'), ('CAIXAS', 'Caixa')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('referencia_externa_tipo', models.CharField(blank=True, max_length=80)),
                ('referencia_externa_id', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=400)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_salario_rh_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_salario_funcionario', to='base.empresa')),
                ('fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_salario', to='rh.fechamentofolhasimplificado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_salario', to='rh.funcionario')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_salario_funcionario', to='base.loja')),
            ],
            options={
                'verbose_name': 'Pagamento de salário',
                'verbose_name_plural': 'Pagamentos de salário',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['empresa', 'data'], name='rh_pagament_empresa_20ed17_idx'), models.Index(fields=['funcionario', 'data'], name='rh_pagament_funcion_83b190_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('referencia_externa_id__gt', '')), fields=('referencia_externa_tipo', 'referencia_externa_id'), name='rh_pagamento_salario_unico_ref_externa')],
            },
        ),
    ]
