# Generated by Django 6.0.3 on 2026-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_pagamento_salario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='dia_envio_cp_auto',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dia do mês (1–28) em que o sistema gera o título no CP da competência anterior. 0 = não enviar automaticamente.'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dia_vencimento_salario',
            field=models.PositiveSmallIntegerField(default=5, help_text='Dia do mês (1–28) do vencimento do título de salário no CP (conta definida só no pagamento).'),
        ),
    ]
