# Generated by Django 6.0.3 on 2026-03-29 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_empresa_alter_produto_codigo_interno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=300)),
                ('cliente_id_erp', models.CharField(blank=True, default='', max_length=32)),
                ('cliente_documento', models.CharField(blank=True, default='', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=80)),
                ('enviado_erp', models.BooleanField(default=False)),
                ('erp_http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('erp_resposta', models.JSONField(blank=True, null=True)),
                ('usuario_registro', models.CharField(blank=True, default='', max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venda Agro',
                'verbose_name_plural': 'Vendas Agro',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemVendaAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id_externo', models.CharField(blank=True, default='', max_length=64)),
                ('codigo', models.CharField(blank=True, default='', max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.vendaagro')),
            ],
            options={
                'verbose_name': 'Item de venda Agro',
                'verbose_name_plural': 'Itens de venda Agro',
            },
        ),
    ]
