# Generated by Django 6.0.3 on 2026-03-29 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_venda_agro_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('endereco', models.CharField(blank=True, default='', max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente Agro',
                'verbose_name_plural': 'Clientes Agro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao_abertura', models.CharField(blank=True, default='', max_length=500)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacao_fechamento', models.CharField(blank=True, default='', max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de caixa',
                'verbose_name_plural': 'Sessões de caixa',
                'ordering': ['-aberto_em'],
            },
        ),
        migrations.AddField(
            model_name='vendaagro',
            name='sessao_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='produtos.sessaocaixa'),
        ),
    ]
