# Generated by Django 6.0.3 on 2026-03-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_clienteagro_endereco_estruturado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('separando', 'Separando'), ('pronto_rota', 'Pronto p/ rota'), ('em_rota', 'Em rota'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('cliente_nome', models.CharField(max_length=300)),
                ('telefone', models.CharField(blank=True, default='', max_length=40)),
                ('endereco_linha', models.CharField(blank=True, default='', max_length=500)),
                ('plus_code', models.CharField(blank=True, default='', max_length=120)),
                ('referencia_rural', models.CharField(blank=True, default='', help_text='Ex.: porteira azul, 2 km após o trevo.', max_length=300)),
                ('maps_url_manual', models.URLField(blank=True, default='', help_text='Link colado do Google Maps (casa no satélite).', max_length=600)),
                ('itens_json', models.JSONField(default=list)),
                ('total_texto', models.CharField(blank=True, default='', max_length=48)),
                ('orc_local_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('retomar_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('operador', models.CharField(blank=True, default='', max_length=120)),
                ('hora_prevista', models.TimeField(blank=True, null=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('hora_entrega', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de entrega',
                'verbose_name_plural': 'Pedidos de entrega',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='clienteagro',
            name='plus_code',
            field=models.CharField(blank=True, default='', help_text='Ex.: 8X5R+7M9 Jacupiranga — abre direto no Google Maps na busca.', max_length=120, verbose_name='Plus Code / local rural (Maps)'),
        ),
    ]
