# Generated by Django 6.0.3 on 2026-03-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_pedido_entrega_e_plus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoentrega',
            name='forma_pagamento',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='pedidoentrega',
            name='troco_precisa',
            field=models.BooleanField(blank=True, help_text='Somente para Dinheiro: True = levar troco, False = sem troco.', null=True, verbose_name='Precisa de troco'),
        ),
    ]
