# Generated by Django 6.0.3 on 2026-04-01 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_entrega_pagamento_troco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoBaixaFinanceiroExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('forma', 'Forma de pagamento'), ('banco', 'Banco / conta')], db_index=True, max_length=16)),
                ('id_erp', models.CharField(blank=True, default='', help_text='Recomendado: copie o ID do cadastro no ERP para manter a baixa alinhada.', max_length=80, verbose_name='ID no ERP / Mongo')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome exibido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_baixa_financeiro_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opção extra (baixa financeira)',
                'verbose_name_plural': 'Opções extras (baixa financeira)',
                'ordering': ['tipo', 'nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_erp__gt', '')), fields=('usuario', 'tipo', 'id_erp'), name='uniq_opcao_baixa_extra_com_id_erp'), models.UniqueConstraint(condition=models.Q(('id_erp', '')), fields=('usuario', 'tipo', 'nome'), name='uniq_opcao_baixa_extra_sem_id_erp')],
            },
        ),
    ]
