# Generated by Django 6.0.3 on 2026-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_pedido_entrega_cliente_agro_cliente_maps_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaagro',
            name='erp_sync_status',
            field=models.CharField(blank=True, choices=[('aceito', 'Aceito no ERP'), ('recusado_erp', 'Recusado pelo ERP'), ('falha_comunicacao', 'Falha na comunicação')], db_index=True, default='', help_text='Resultado do envio ao ERP (Pedidos/Salvar). Vazio = registro antigo antes deste campo.', max_length=24),
        ),
    ]
