# Generated by Django 6.0.3 on 2026-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_venda_agro_erp_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaagro',
            name='estoque_baixa_agro_aplicada',
            field=models.BooleanField(db_index=True, default=False, help_text='Se True, já foi registrada baixa de estoque na camada Agro (AjusteRapidoEstoque) para esta venda.'),
        ),
    ]
