# Generated by Django 6.0.3 on 2026-04-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_venda_estoque_baixa_agro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoAtalhoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(db_index=True, help_text='1 ou 2 — identifica o botão na barra.')),
                ('nome', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamento_atalhos_filtro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atalho de filtro (lançamentos)',
                'verbose_name_plural': 'Atalhos de filtro (lançamentos)',
                'ordering': ['usuario_id', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'slot'), name='uniq_lancamento_atalho_filtro_usuario_slot')],
            },
        ),
    ]
