# Generated by Django 6.0.3 on 2026-04-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_lancamento_atalho_filtro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdvMercadoPagoPointOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mp_order_id', models.CharField(db_index=True, max_length=80)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('erp_payload', models.JSONField()),
                ('django_session_key', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('finalized', 'Finalizado (ERP)'), ('failed', 'Falha')], db_index=True, default='pending', max_length=20)),
                ('mp_last_status', models.CharField(blank=True, default='', max_length=48)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mp_point', to='produtos.vendaagro')),
            ],
            options={
                'verbose_name': 'Pedido Mercado Pago Point (PDV)',
                'verbose_name_plural': 'Pedidos Mercado Pago Point (PDV)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
