# Generated by Django 6.0.3 on 2026-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_pdv_mercado_pago_point_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdvmercadopagopointorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando pagamento'), ('abandoned', 'Abandonado pelo operador'), ('finalized', 'Finalizado (ERP)'), ('failed', 'Falha')], db_index=True, default='pending', max_length=20),
        ),
    ]
