# Generated by Django 6.0.3 on 2026-04-11 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_produto_grupo_agro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGestaoOverlayAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID produto (Mongo/ERP)')),
                ('nome', models.CharField(blank=True, default='', max_length=300)),
                ('marca', models.CharField(blank=True, default='', max_length=120)),
                ('categoria', models.CharField(blank=True, default='', max_length=200)),
                ('fornecedor_texto', models.CharField(blank=True, default='', max_length=300)),
                ('unidade', models.CharField(blank=True, default='', max_length=20)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço de venda (override)')),
                ('ativo_exibicao', models.BooleanField(blank=True, help_text='None = seguir ERP; True/False forçar exibição de status.', null=True, verbose_name='Ativo na listagem')),
                ('estoque_min_centro', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estoque_max_centro', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estoque_min_vila', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estoque_max_vila', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_overlays_gestao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overlay gestão de produto',
                'verbose_name_plural': 'Overlays gestão de produtos',
            },
        ),
    ]
