# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0018_produtogestaooverlayagro_codigo_campos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoMarcaVariacaoAgro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("produto_externo_id", models.CharField(db_index=True, max_length=64, verbose_name="ID produto (Mongo/ERP)")),
                ("marca", models.CharField(max_length=120)),
                ("codigo_barras", models.CharField(blank=True, default="", max_length=80)),
                ("codigo_fornecedor", models.CharField(blank=True, default="", max_length=80)),
                ("estoque", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("custo_unitario", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Variação de marca (cadastro mestre)",
                "verbose_name_plural": "Variações de marca (cadastro mestre)",
                "ordering": ["produto_externo_id", "ordem", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="produtomarcavariacaoagro",
            index=models.Index(fields=["codigo_barras"], name="pmva_codigo_barras"),
        ),
        migrations.AddIndex(
            model_name="produtomarcavariacaoagro",
            index=models.Index(fields=["codigo_fornecedor"], name="pmva_codigo_forn"),
        ),
    ]
