# Generated by Django 6.0.3 on 2026-04-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_produto_marca_variacao_agro'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produtomarcavariacaoagro',
            name='pmva_codigo_barras',
        ),
        migrations.RemoveIndex(
            model_name='produtomarcavariacaoagro',
            name='pmva_codigo_forn',
        ),
    ]
