# Generated by Django 6.0.3 on 2026-04-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_produtogestaooverlayagro_cadastro_extras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo', models.CharField(max_length=100, verbose_name='Código do lote')),
                ('data_validade', models.DateField(verbose_name='Data de validade')),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade atual')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produtos.produtogestaooverlayagro')),
            ],
            options={
                'verbose_name': 'Estoque por lote (Agro)',
                'verbose_name_plural': 'Estoque por lote (Agro)',
                'ordering': ['data_validade', 'id'],
                'constraints': [models.UniqueConstraint(fields=('overlay', 'lote_codigo'), name='uniq_estoque_lote_overlay_lote')],
            },
        ),
    ]
