# Generated by Django 6.0.3 on 2026-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0034_promocao_permanente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cadastro_inativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='cadastro_somente_agro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_nfe',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='erp_produto_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID decimal/nativo para Pedidos/Salvar no ERP legado.', max_length=64),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_texto',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_externo_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='ID legado Mongo/ERP'),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria_4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidoentrega',
            name='aguarda_pagamento_pdv',
            field=models.BooleanField(db_index=True, default=False, help_text='Venda do PDV pendente até fechar pagamento após a entrega.', verbose_name='Aguarda pagamento no PDV'),
        ),
        migrations.AlterField(
            model_name='pedidoentrega',
            name='pdv_wizard_state',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot do wizard PDV para retomar no pagamento.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vendaagro',
            name='erp_sync_status',
            field=models.CharField(blank=True, choices=[('pendente', 'Aguardando ERP'), ('aceito', 'Aceito no ERP'), ('recusado_erp', 'Recusado pelo ERP'), ('falha_comunicacao', 'Falha na comunicação')], db_index=True, default='', help_text='Resultado do envio ao ERP (Pedidos/Salvar). Vazio = registro antigo antes deste campo.', max_length=24),
        ),
    ]
