# Generated by Django 6.0.3 on 2026-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0040_vendaagro_nfce_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcedocumentoagro',
            name='status',
            field=models.CharField(choices=[('autorizada', 'Autorizada'), ('cancelada', 'Cancelada'), ('rejeitada', 'Rejeitada'), ('erro', 'Erro técnico')], db_index=True, max_length=16),
        ),
        migrations.CreateModel(
            name='TituloFinanceiroAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(db_index=True, help_text='ObjectId string do DtoLancamento (idempotência).', max_length=32, unique=True)),
                ('despesa', models.BooleanField(db_index=True, help_text='True = contas a pagar; False = contas a receber.')),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('cliente', models.CharField(blank=True, default='', max_length=300)),
                ('cliente_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('numero_documento', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('parcela', models.PositiveSmallIntegerField(default=0)),
                ('plano_conta', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('plano_conta_id', models.CharField(blank=True, default='', max_length=32)),
                ('grupo', models.CharField(blank=True, default='', max_length=200)),
                ('forma_pagamento', models.CharField(blank=True, default='', max_length=120)),
                ('forma_pagamento_id', models.CharField(blank=True, default='', max_length=32)),
                ('banco', models.CharField(blank=True, default='', max_length=120)),
                ('banco_id', models.CharField(blank=True, default='', max_length=32)),
                ('centro_custo', models.CharField(blank=True, default='', max_length=120)),
                ('empresa', models.CharField(blank=True, default='', max_length=200)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_restante', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quitado', models.BooleanField(db_index=True, default=False)),
                ('data_vencimento', models.DateField(blank=True, db_index=True, null=True)),
                ('data_competencia', models.DateField(blank=True, db_index=True, null=True)),
                ('data_fluxo', models.DateField(blank=True, db_index=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, db_index=True, null=True)),
                ('agro_recorrente', models.BooleanField(default=False)),
                ('recorrencia_intervalo_meses', models.PositiveSmallIntegerField(default=1)),
                ('agro_recorrente_sempre', models.BooleanField(default=False)),
                ('boleto_codigo_barras', models.CharField(blank=True, default='', max_length=54)),
                ('usuario_lancou', models.CharField(blank=True, default='', max_length=150)),
                ('usuario_quitou', models.CharField(blank=True, default='', max_length=150)),
                ('modificado_por', models.CharField(blank=True, default='', max_length=200)),
                ('criado_por', models.CharField(blank=True, default='', max_length=200)),
                ('mongo_congelado', models.BooleanField(default=False, help_text='``AgroFonteVerdade`` no documento Mongo.')),
                ('mongo_ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('dados_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Título financeiro Agro',
                'verbose_name_plural': 'Títulos financeiros Agro',
                'ordering': ['-data_vencimento', 'pk'],
                'indexes': [models.Index(fields=['despesa', 'quitado', 'data_vencimento'], name='produtos_ti_despesa_74dfcb_idx')],
            },
        ),
    ]
