# Generated by Django 6.0.3 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0041_titulo_financeiro_agro"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vendaagro",
            index=models.Index(fields=["-criado_em"], name="vendaagro_criado_em_idx"),
        ),
    ]
