# Generated by Django 6.0.3 on 2026-06-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0042_vendaagro_criado_em_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaNotaRascunhoAgro',
            fields=[
                ('rascunho_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='com_pendencias', max_length=40)),
                ('modo', models.CharField(blank=True, default='manual', max_length=40)),
                ('usuario', models.CharField(blank=True, default='', max_length=200)),
                ('usuario_ultima_alteracao', models.CharField(blank=True, default='', max_length=200)),
                ('usuario_estoque_aplicado', models.CharField(blank=True, default='', max_length=200)),
                ('xml_chave', models.CharField(blank=True, default='', max_length=44)),
                ('cabecalho', models.JSONField(blank=True, default=dict)),
                ('linhas', models.JSONField(blank=True, default=list)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(db_index=True)),
                ('atualizado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('estoque_aplicado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rascunho Entrada NF Agro',
                'verbose_name_plural': 'Rascunhos Entrada NF Agro',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='produtos_en_criado__b0d79e_idx'), models.Index(fields=['status', '-atualizado_em'], name='produtos_en_status_d241ec_idx')],
            },
        ),
    ]
