# Generated by Django 6.0.3 on 2026-06-29 02:40

from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def _seed_planilha_vendas(apps, schema_editor):
    path = Path(settings.BASE_DIR) / "docs" / "dados" / "vendas_centro_nov2025.xlsx"
    if not path.is_file():
        return
    from produtos.dashboard_vendas_historico_util import importar_dashboard_vendas_historico_xlsx

    importar_dashboard_vendas_historico_xlsx(path)


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0044_limpar_rascunho_entrada_nf_id_invalido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVendaDiaHistoricoAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True, verbose_name='Data')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total (R$)')),
                ('deposito', models.CharField(blank=True, default='centro', help_text='centro · vila — planilha Renan hoje é só Centro.', max_length=16, verbose_name='Depósito')),
                ('fonte', models.CharField(blank=True, default='planilha', max_length=64, verbose_name='Fonte')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venda diária histórico BI',
                'verbose_name_plural': 'Vendas diárias histórico BI',
                'ordering': ['-data'],
            },
        ),
        migrations.RunPython(_seed_planilha_vendas, migrations.RunPython.noop),
    ]
