# Generated by Django 6.0.3 on 2026-07-14 16:25

from django.db import migrations, models


def _copiar_modelo_do_overlay(apps, schema_editor):
    Produto = apps.get_model("produtos", "Produto")
    Overlay = apps.get_model("produtos", "ProdutoGestaoOverlayAgro")
    for ov in Overlay.objects.all().iterator(chunk_size=200):
        ce = ov.cadastro_extras if isinstance(ov.cadastro_extras, dict) else {}
        modelo = str(ce.get("modelo") or "").strip()[:200]
        if not modelo:
            continue
        pid = str(ov.produto_externo_id or "").strip()[:64]
        if not pid:
            continue
        Produto.objects.filter(produto_externo_id=pid).exclude(modelo=modelo).update(modelo=modelo)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        # Irmã da 0050 (frete): loja pode receber 0051 sem a 0050.
        ("produtos", "0049_plano_unificacao_lote_agro"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="modelo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Modelo/versão do produto (cadastro SisVale).",
                max_length=200,
                verbose_name="Modelo",
            ),
        ),
        migrations.RunPython(_copiar_modelo_do_overlay, _noop_reverse),
    ]
