# Generated by Django 6.0.3 on 2026-07-17 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0053_devolucao_parcial_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdvmercadopagopointorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Pago no terminal'), ('abandoned', 'Abandonado pelo operador'), ('finalized', 'Finalizado (ERP)'), ('failed', 'Falha')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProdutoCadastroAlteracaoAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=64)),
                ('campo', models.CharField(db_index=True, max_length=64)),
                ('campo_label', models.CharField(blank=True, default='', max_length=80)),
                ('valor_antes', models.CharField(blank=True, default='', max_length=500)),
                ('valor_depois', models.CharField(blank=True, default='', max_length=500)),
                ('origem', models.CharField(choices=[('modal', 'Modal cadastro'), ('gestao', 'Gestão'), ('planilha', 'Excel'), ('nf', 'Entrada NF'), ('outro', 'Outro')], db_index=True, default='outro', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_cadastro_alteracoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alteração cadastro produto',
                'verbose_name_plural': 'Alterações cadastro produto',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['produto_externo_id', '-criado_em'], name='prod_cad_alt_pid_criado_idx')],
            },
        ),
    ]
