# Generated by Django 6.0.3 on 2026-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0063_agronfedistdfecursor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenserDocumentoAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('folha', 'Folha pronta'), ('layout', 'Modelo de layout')], db_index=True, max_length=20)),
                ('nome', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('thumb', models.TextField(blank=True, default='', help_text='Miniatura JPEG/PNG (data URL ou base64).')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispenser A6 · documento',
                'verbose_name_plural': 'Dispenser A6 · documentos',
                'indexes': [models.Index(fields=['tipo', 'atualizado_em'], name='dsp_doc_tipo_upd_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nome'), name='uniq_dispenser_doc_tipo_nome')],
            },
        ),
        migrations.CreateModel(
            name='DispenserMidiaAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('logo', 'Logo'), ('pet', 'Pet'), ('ing', 'Ingrediente'), ('flavor_ico', 'Ícone de sabor')], db_index=True, max_length=20)),
                ('item_id', models.CharField(db_index=True, max_length=80)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('data_base64', models.TextField(blank=True, default='')),
                ('mime', models.CharField(blank=True, default='image/png', max_length=40)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispenser A6 · mídia',
                'verbose_name_plural': 'Dispenser A6 · mídias',
                'indexes': [models.Index(fields=['tipo', 'atualizado_em'], name='dsp_midia_tipo_upd_idx')],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'item_id'), name='uniq_dispenser_midia_tipo_item')],
            },
        ),
    ]
