# Generated by Django 6.0.3 on 2026-07-31 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_uso_loja_retirada'),
        ('produtos', '0072_agronfedistdfe_tabelas_se_faltar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoLojaRetiradaAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(db_index=True, max_length=20)),
                ('quem_levou', models.CharField(max_length=120)),
                ('motivo', models.CharField(blank=True, default='', max_length=40)),
                ('operador_pin', models.CharField(max_length=120)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estornado', models.BooleanField(db_index=True, default=False)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('estornado_por', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Uso loja · retirada',
                'verbose_name_plural': 'Uso loja · retiradas',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UsoLojaRetiradaItemAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=100)),
                ('codigo_interno', models.CharField(blank=True, default='', max_length=100)),
                ('nome_produto', models.CharField(blank=True, default='', max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
            options={
                'verbose_name': 'Uso loja · item',
                'verbose_name_plural': 'Uso loja · itens',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='usolojaretiradaagro',
            name='sessao_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_loja_retiradas', to='produtos.sessaocaixa'),
        ),
        migrations.AddField(
            model_name='usolojaretiradaagro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_loja_retiradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usolojaretiradaitemagro',
            name='ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_loja_itens', to='estoque.ajusterapidoestoque'),
        ),
        migrations.AddField(
            model_name='usolojaretiradaitemagro',
            name='ajuste_estorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_loja_itens_estorno', to='estoque.ajusterapidoestoque'),
        ),
        migrations.AddField(
            model_name='usolojaretiradaitemagro',
            name='retirada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.usolojaretiradaagro'),
        ),
    ]
