# Generated by Django 6.0.3 on 2026-08-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0082_plano_conta_agro'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronfedistdfedocumento',
            name='manifestacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agronfedistdfedocumento',
            name='manifestacao_mensagem',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='agronfedistdfedocumento',
            name='manifestacao_protocolo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='agronfedistdfedocumento',
            name='manifestacao_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
