# Generated by Django 6.0.3 on 2026-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0089_itemvendaagro_unidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaixaConferenciaRascunhoAgro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turno_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("rascunho_json", models.JSONField(blank=True, default=dict)),
                ("cedulas_json", models.JSONField(blank=True, default=dict)),
                ("atualizado_por", models.CharField(blank=True, default="", max_length=120)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rascunho contagem fechar caixa",
                "verbose_name_plural": "Rascunhos contagem fechar caixa",
                "ordering": ["-atualizado_em"],
            },
        ),
    ]
