# Generated by Django 6.0.3 on 2026-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0100_repasse_vila_cofrinho'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agronfedistdfedocumento',
            new_name='produtos_ag_cnpj_cac93a_idx',
            old_name='produtos_ag_cnpj_dfe_idx',
        ),
        migrations.AlterField(
            model_name='produtocadastroalteracaoagro',
            name='origem',
            field=models.CharField(choices=[('modal', 'Modal cadastro'), ('pdv', 'PDV edição rápida'), ('gestao', 'Gestão'), ('planilha', 'Excel'), ('nf', 'Entrada NF'), ('outro', 'Outro')], db_index=True, default='outro', max_length=16),
        ),
    ]
