# Generated by Django 6.0.3 on 2026-08-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0101_rename_produtos_ag_cnpj_dfe_idx_produtos_ag_cnpj_cac93a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repassevilareservamovimentoagro',
            name='origem',
            field=models.CharField(choices=[('fechamento_caixa', 'Fechamento de caixa'), ('repasse', 'Repasse Vila → Centro'), ('lancamento_separado', 'Lançamento separado'), ('ajuste_manual', 'Ajuste manual'), ('saldo_inicial', 'Saldo inicial'), ('estorno', 'Estorno')], db_index=True, max_length=24),
        ),
    ]
