# Generated by Django 6.0.3 on 2026-08-29 12:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_duas_tabelas(apps, schema_editor):
    Tabela = apps.get_model("produtos", "TabelaPrecoFormaAgro")
    for slot, nome in ((1, "Tabela 1"), (2, "Tabela 2")):
        Tabela.objects.get_or_create(
            slot=slot,
            defaults={
                "nome": nome,
                "ativo": False,
                "percentual": Decimal("0"),
                "arredondar_dezena_centavos": False,
                "formas": [],
                "categorias_vetadas": [],
                "produtos_vetados": [],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0103_dois_cofrinhos_vila'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPrecoFormaAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='1 ou 2', unique=True, verbose_name='Slot')),
                ('nome', models.CharField(default='Tabela', max_length=80, verbose_name='Nome')),
                ('ativo', models.BooleanField(db_index=True, default=False, verbose_name='Ativa')),
                ('percentual', models.DecimalField(decimal_places=4, default=0, help_text='Ex.: −0,55 = desconto 0,55%; +1,5 = acréscimo 1,5%.', max_digits=8, verbose_name='% desconto (−) ou acréscimo (+)')),
                ('arredondar_dezena_centavos', models.BooleanField(default=False, help_text='≤4 desce · ≥5 sobe (ex.: 10,43→10,40 · 10,45→10,50).', verbose_name='Arredondar à dezena de centavos')),
                ('formas', models.JSONField(blank=True, default=list, help_text='Ex.: ["Fiado", "Cartão de crédito"]', verbose_name='Formas de pagamento')),
                ('categorias_vetadas', models.JSONField(blank=True, default=list, verbose_name='Categorias vetadas')),
                ('produtos_vetados', models.JSONField(blank=True, default=list, verbose_name='Produtos vetados (ids)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela preço % por forma',
                'verbose_name_plural': 'Tabelas preço % por forma',
                'ordering': ['slot'],
            },
        ),
        migrations.AddField(
            model_name='promocaoagro',
            name='preco_y_t1',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço Y quando a forma cair na Tabela 1 global; vazio = usa preco_y.', max_digits=12, null=True, verbose_name='Preço Y · Tabela 1'),
        ),
        migrations.AddField(
            model_name='promocaoagro',
            name='preco_y_t2',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço Y quando a forma cair na Tabela 2 global; vazio = usa preco_y.', max_digits=12, null=True, verbose_name='Preço Y · Tabela 2'),
        ),
        migrations.AddField(
            model_name='promocaoagro',
            name='regra_vs_tabela',
            field=models.CharField(blank=True, default='maior', help_text='maior | promo | tabela — default da promo; item pode sobrescrever.', max_length=16, verbose_name='Regra promo × tabela %'),
        ),
        migrations.AddField(
            model_name='promocaoagro',
            name='resolucoes_vs_tabela',
            field=models.JSONField(blank=True, default=dict, help_text='{"produto_id": "maior"|"promo"|"tabela"}', verbose_name='Resoluções promo × tabela por produto'),
        ),
        migrations.AddField(
            model_name='promocaoprodutoagro',
            name='preco_promocional_t1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Preço promo · Tabela 1'),
        ),
        migrations.AddField(
            model_name='promocaoprodutoagro',
            name='preco_promocional_t2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Preço promo · Tabela 2'),
        ),
        migrations.CreateModel(
            name='TabelaPrecoFormaResolucaoAgro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_externo_id', models.CharField(db_index=True, max_length=64)),
                ('preferencia', models.CharField(choices=[('tabela', 'Usar tabela %'), ('individual', 'Manter individual')], default='individual', max_length=16)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucoes', to='produtos.tabelaprecoformaagro')),
            ],
            options={
                'verbose_name': 'Resolução tabela % × individual',
                'verbose_name_plural': 'Resoluções tabela % × individual',
                'constraints': [models.UniqueConstraint(fields=('tabela', 'produto_externo_id'), name='uniq_tabela_preco_forma_resolucao')],
            },
        ),
        migrations.RunPython(seed_duas_tabelas, migrations.RunPython.noop),
    ]
