# Generated by Django 6.0.3 on 2026-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0108_atendimento_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconversaagro',
            name='loja',
            field=models.CharField(choices=[('pendente', 'Fila (escolhe loja)'), ('centro', 'Centro'), ('vila', 'Vila Elias')], db_index=True, default='pendente', max_length=16),
        ),
        migrations.AlterField(
            model_name='whatsappmensagemagro',
            name='direcao',
            field=models.CharField(choices=[('in', 'Cliente'), ('out', 'Loja'), ('bot', 'Bot')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='whatsappponteestadoagro',
            name='status',
            field=models.CharField(choices=[('desconectado', 'Desconectado'), ('qr', 'Aguardando QR'), ('conectado', 'Conectado')], db_index=True, default='desconectado', max_length=20),
        ),
    ]
