"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
DEBUG = True
import os

import dj_database_url
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',') if host.strip()]

# Render injeta RENDER=true; sem isso, ALLOWED_HOSTS só com localhost → 400 DisallowedHost no deploy.
_on_render = str(os.environ.get("RENDER", "")).lower() in ("1", "true", "yes")
if _on_render and ".onrender.com" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + [".onrender.com"]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
    "https://agro-consulta.onrender.com",
]
if _on_render and "https://*.onrender.com" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + ["https://*.onrender.com"]

# Painel BI (/, /dashboard/gerencial/, HTMX parcial e feed) sem exigir login.
# Padrão True (painel aberto). Para exigir login de novo: AGRO_PUBLIC_DASHBOARD=false no .env / Render.
# POST de sync ERP continua com login; ?sync=1 na URL só roda se já autenticado.
AGRO_PUBLIC_DASHBOARD = config("AGRO_PUBLIC_DASHBOARD", default=True, cast=bool)

# Após ERP v3: espelho Mongo (agregação no servidor). Default True = alinhado ao gráfico do BI;
# defina false só se a instância esgotar RAM (worker).
AGRO_DASHBOARD_MONGO_RANKING_FALLBACK = config(
    "AGRO_DASHBOARD_MONGO_RANKING_FALLBACK", default=True, cast=bool
)

# Relatórios HTTP v3 no dashboard (PedidosItens / CondensadoVendedor). False = pula ERP e vai direto ao SQLite.
AGRO_DASHBOARD_ERP_V3_REPORTS = config("AGRO_DASHBOARD_ERP_V3_REPORTS", default=True, cast=bool)

# Timeout por tentativa GET/POST em /v3/.../Report (segundos). Muitas tentativas × timeout alto travava o worker.
AGRO_ERP_V3_REPORT_TIMEOUT_SEC = config(
    "AGRO_ERP_V3_REPORT_TIMEOUT_SEC", default=8, cast=int
)

# Teto de bytes lido por relatório v3 (resposta JSON pode ser enorme; ultrapassar evita OOM no worker).
AGRO_ERP_V3_REPORT_MAX_BYTES = config("AGRO_ERP_V3_REPORT_MAX_BYTES", default=4_000_000, cast=int)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'base',
    'rh',

    'rest_framework',

    'financeiro',
    'lojas',
    'pdv.apps.PdvConfig',
    'produtos',
    'estoque',
    'transferencias',
    'relatorios',
    'integracoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Idempotência global (header Idempotency-Key / X-Agro-Client-Request-Id ou body client_request_id)
    'base.middleware.AgroIdempotencyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- Idempotência HTTP (duplo clique / retry) — ver base/middleware.py ---
AGRO_IDEMPOTENCY_ENABLED = config('AGRO_IDEMPOTENCY_ENABLED', default=True, cast=bool)
AGRO_IDEMPOTENCY_EXEMPT_PREFIXES = tuple(
    p.strip()
    for p in config(
        'AGRO_IDEMPOTENCY_EXEMPT_PREFIXES',
        default='/admin/,/static/,/media/,/healthz',
    ).split(',')
    if p.strip()
)
AGRO_IDEMPOTENCY_MAX_BODY_PARSE = config('AGRO_IDEMPOTENCY_MAX_BODY_PARSE', default=524288, cast=int)
AGRO_IDEMPOTENCY_MAX_RESPONSE_BYTES = config('AGRO_IDEMPOTENCY_MAX_RESPONSE_BYTES', default=524288, cast=int)
AGRO_IDEMPOTENCY_CACHE_TTL = config('AGRO_IDEMPOTENCY_CACHE_TTL', default=86400, cast=int)
AGRO_IDEMPOTENCY_LOCK_TTL = config('AGRO_IDEMPOTENCY_LOCK_TTL', default=120, cast=int)
ROOT_URLCONF = 'config.urls'
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# No Render: sem manifest evita 500 em runtime se algum asset faltar no manifest pós-collectstatic
# (o edge costuma devolver 502 quando o worker cai ou responde mal).
if _on_render:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#sadasdas#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'base' / 'templates'], # Caminho absoluto para a pasta que você criou
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
VENDA_ERP_MONGO_URL = config('VENDA_ERP_MONGO_URL', default='')
VENDA_ERP_MONGO_DB = config('VENDA_ERP_MONGO_DB', default='')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'agro-consulta-cache',
    }
}

CONSULTA_CACHE_TTL = 20
# Configurações da API Venda ERP
# Contrato OpenAPI (substitua o subdomínio pelo da sua instância WL, o mesmo host de VENDA_ERP_API_BASE_URL quando for o caso):
#   https://<subdominio>.vendaerp.com.br/api/swagger/index.html
# Endpoints usados pelo Agro costumam estar sob /api/request/... (ex.: Pedidos/Salvar).
VENDA_ERP_API_BASE_URL = config('VENDA_ERP_API_BASE_URL', default='https://cw.vendaerp.com.br')
VENDA_ERP_API_TOKEN = config('VENDA_ERP_API_TOKEN', default='')
# Financeiro: sufixo após /api/request/ (ex.: Lancamentos/SalvarBaixa). Vazio = não chama API.
VENDA_ERP_API_FINANCEIRO_BAIXA_PATH = config('VENDA_ERP_API_FINANCEIRO_BAIXA_PATH', default='').strip()
VENDA_ERP_API_FINANCEIRO_LANCAMENTO_PATH = config('VENDA_ERP_API_FINANCEIRO_LANCAMENTO_PATH', default='').strip()

# DRE (resumo por plano): resultado | resultado_erp (colunas 1/5 receita · 2/10/11/12 despesa, como o PDF) | todas.
DRE_RESULTADO_FILTRO = (config('DRE_RESULTADO_FILTRO', default='resultado') or 'resultado').strip().lower()
# Padrões extras de exclusão (separar com ||), mesclados ao filtro "resultado".
DRE_RESULTADO_EXCLUIR_REGEX_EXTRA = config('DRE_RESULTADO_EXCLUIR_REGEX_EXTRA', default='').strip()
# DRE: agrupa linhas cujo PlanoDeConta só difere pelo código hierárquico (ex.: "1.1.1 — Vendas Pdv" + "Vendas Pdv").
DRE_MESCLAR_PLANO_PREFIXO_CODIGO = config('DRE_MESCLAR_PLANO_PREFIXO_CODIGO', default=True, cast=bool)
# Ao mesclar pelo nome sem código, se houver pai (1.1) e filho (1.1.1) com o mesmo nome base, somente o mais profundo entra (evita ~2x na receita).
DRE_MESCLAR_PLANO_PROFUNDIDADE_MAX = config('DRE_MESCLAR_PLANO_PROFUNDIDADE_MAX', default=True, cast=bool)
# DRE: não soma contas-pai quando já existem filhos no mesmo relatório (ex.: não somar 1 + 1.1 + 1.1.1).
DRE_EXCLUIR_PLANOS_PAI_HIERARQUIA = config('DRE_EXCLUIR_PLANOS_PAI_HIERARQUIA', default=True, cast=bool)
# DRE: remove plano sem código no texto se o mesmo nome (normalizado) já existe num plano com código (ex.: "Manutenção Frota" duplicando 2.1.7.3).
DRE_ZERAR_SEM_CODIGO_REPETE_PAI = config('DRE_ZERAR_SEM_CODIGO_REPETE_PAI', default=True, cast=bool)
# DRE: colapsa documentos duplicados no Mongo com o mesmo Id/LancamentoID do ERP antes de somar.
DRE_DEDUP_LANCAMENTO_ID = config('DRE_DEDUP_LANCAMENTO_ID', default=True, cast=bool)
# Sem Id/LancamentoID, o fallback antigo era ``_id`` (cada cópia duplicada = chave diferente → total ~2x).
# Com True, usa assinatura (empresa, data, plano, valor DRE, doc., parcela, cliente) para colapsar cópias idênticas.
DRE_DEDUP_ASSINATURA_SEM_ID = config('DRE_DEDUP_ASSINATURA_SEM_ID', default=True, cast=bool)
# Tela dedicada /lancamentos/dre/ e item no menu lateral. False = rota mostra aviso “desativado”.
LANCAMENTOS_DRE_ATIVO = config('LANCAMENTOS_DRE_ATIVO', default=False, cast=bool)
# True = logs [FINANCEIRO_RESUMO_DIAG] no logger financeiro.resumo_diagnostico (ou use ?debug_resumo=1 na API).
FINANCEIRO_DEBUG_RESUMO = config('FINANCEIRO_DEBUG_RESUMO', default=False, cast=bool)

# Saída no caixa (/caixa/saida/): nomes para “quem levou o dinheiro”, separados por vírgula. Vazio = só “Outro”.
AGRO_SAIDA_CAIXA_FUNCIONARIOS = config('AGRO_SAIDA_CAIXA_FUNCIONARIOS', default='').strip()
AGRO_SAIDA_CAIXA_EMPRESA_PADRAO = config('AGRO_SAIDA_CAIXA_EMPRESA_PADRAO', default='Agro Mais Centro').strip()

# RH: texto de PlanoDeConta no Mongo para o título único de salário (despesa). Deve existir no ERP.
AGRO_RH_PLANO_SALARIO_FOLHA = (config("AGRO_RH_PLANO_SALARIO_FOLHA", default="") or "").strip() or (
    "2.1.1.1.2 — Salários"
)
# Conta placeholder no ERP (ex.: «ADICIONAR BANCO») até definir banco real — BancoID como string no Mongo/cadastro.
# Se vazio, o Agro usa um ID legado embutido; defina no .env o ID correto da sua base (veja um DtoLancamento que já use essa conta).
AGRO_FINANCEIRO_BANCO_PLACEHOLDER_ID = (
    config("AGRO_FINANCEIRO_BANCO_PLACEHOLDER_ID", default="") or ""
).strip()
AGRO_FINANCEIRO_BANCO_PLACEHOLDER_NOME = (
    (config("AGRO_FINANCEIRO_BANCO_PLACEHOLDER_NOME", default="") or "").strip()
    or "ADICIONAR BANCO"
)

# Empréstimos: texto de ``PlanoDeConta`` no Mongo exatamente como no ERP (sobrescreve o padrão do código).
# Vazio = usa padrão em ``mongo_financeiro_util`` + regex legada (com/sem acento).
AGRO_EMPRESTIMO_PLANO_ENTRADA = (config("AGRO_EMPRESTIMO_PLANO_ENTRADA", default="") or "").strip()
AGRO_EMPRESTIMO_PLANO_DIVIDA = (config("AGRO_EMPRESTIMO_PLANO_DIVIDA", default="") or "").strip()
AGRO_EMPRESTIMO_PLANO_JUROS = (config("AGRO_EMPRESTIMO_PLANO_JUROS", default="") or "").strip()
# Empréstimos — consulta: nomes de cliente (Mongo) a ocultar na lista, separados por vírgula (normalização case-insensitive).
AGRO_EMPRESTIMO_EXCLUIR_CLIENTES = (config("AGRO_EMPRESTIMO_EXCLUIR_CLIENTES", default="") or "").strip()

# PDV: WhatsApp para aviso de separação/entrega ao salvar orçamento (somente dígitos, ex.: 5513999999999).
# wa.me abre conversa com um número; não existe URL oficial para “postar” direto em grupo pelo navegador.
# Para grupo: API (ex. WhatsApp Business), ou número da loja que repassa no grupo manualmente.
PDV_ENTREGA_WHATSAPP = config('PDV_ENTREGA_WHATSAPP', default='5513997673389').strip()
# PDV Wizard — etapa pagamento: QR estáticos (URL de imagem), chave Pix e saldos exibidos (vale/cashback até integrar API).
PDV_QR_MERCADOPAGO_URL = config("PDV_QR_MERCADOPAGO_URL", default="").strip()
# Mercado Pago Point — cobrança enviada ao terminal (API Orders). Ver produtos/views_mp_point.py
MP_POINT_ENABLED = config("MP_POINT_ENABLED", default=False, cast=bool)
MP_POINT_ACCESS_TOKEN = (config("MP_POINT_ACCESS_TOKEN", default="") or "").strip()
MP_POINT_TERMINAL_ID = (config("MP_POINT_TERMINAL_ID", default="") or "").strip()
MP_POINT_EXPIRATION = (config("MP_POINT_EXPIRATION", default="PT16M") or "PT16M").strip()
MP_POINT_PRINT_ON_TERMINAL = (
    config("MP_POINT_PRINT_ON_TERMINAL", default="no_ticket") or "no_ticket"
).strip()
PDV_QR_SICREDI_URL = config("PDV_QR_SICREDI_URL", default="").strip()
PDV_CHAVE_PIX_SICOB = config("PDV_CHAVE_PIX_SICOB", default="").strip()
# Venda ERP — POST Pedidos/Salvar: literal exato do status (enum no ERP; maiúsculas importam).
# Muitas instâncias usam "Pedido" (Title case), não "PEDIDO". Sobrescreva no .env se o seu for outro.
_VENDA_ERP_PEDIDO_STATUS_SISTEMA_RAW = config("VENDA_ERP_PEDIDO_STATUS_SISTEMA", default="Pedido").strip()
VENDA_ERP_PEDIDO_STATUS_SISTEMA = _VENDA_ERP_PEDIDO_STATUS_SISTEMA_RAW or "Pedido"
# Pedidos/Salvar: plano de contas (texto como no ERP, ex.: código hierárquico + nome).
_VENDA_ERP_PEDIDO_PLANO_CONTA_RAW = config(
    "VENDA_ERP_PEDIDO_PLANO_CONTA",
    default="1.1.3 — Vendas SisVale",
).strip()
VENDA_ERP_PEDIDO_PLANO_CONTA = (
    _VENDA_ERP_PEDIDO_PLANO_CONTA_RAW or "1.1.3 — Vendas SisVale"
)
# Opcional: PlanoDeContaID (string Mongo) quando o ERP não resolve só pelo texto.
VENDA_ERP_PEDIDO_PLANO_CONTA_ID = config(
    "VENDA_ERP_PEDIDO_PLANO_CONTA_ID",
    default="69d2e2d35c5d14cb68c6acef",
).strip()
# True = primeira tentativa Pedidos/Salvar já em PascalCase (StatusSistema, Items, …).
VENDA_ERP_PEDIDOS_SALVAR_JSON_PASCAL = config(
    "VENDA_ERP_PEDIDOS_SALVAR_JSON_PASCAL", default=False, cast=bool
)
# Se HTTP 200 mas o ERP recusa (ex.: status inválido), tenta de novo o mesmo corpo em PascalCase.
VENDA_ERP_PEDIDOS_SALVAR_RETRY_PASCAL_EM_RECUSA = config(
    "VENDA_ERP_PEDIDOS_SALVAR_RETRY_PASCAL_EM_RECUSA", default=True, cast=bool
)
# Swagger do WL tipicamente declara ``planoDeConta`` como string (literal igual ao cadastro), não objeto.
# True = envia só essa string (sem planoConta / *ID* no JSON). False = envia também aliases e IDs (legado).
VENDA_ERP_PEDIDOS_SALVAR_PLANO_SO_TEXTO_SWAGGER = config(
    "VENDA_ERP_PEDIDOS_SALVAR_PLANO_SO_TEXTO_SWAGGER", default=True, cast=bool
)
# O schema público do Pedidos/Salvar não declara ``planoDeConta`` dentro de ``items`` (só no cabeçalho).
# False = alinhado ao Swagger. True = repete plano em cada linha (legado / WL que exija por item).
VENDA_ERP_PEDIDOS_SALVAR_PLANO_NOS_ITENS = config(
    "VENDA_ERP_PEDIDOS_SALVAR_PLANO_NOS_ITENS", default=False, cast=bool
)
# True = primeiro POST com ``planoDeConta`` como objeto { Id, Nome, … } (fora do schema string do Swagger).
VENDA_ERP_PEDIDOS_SALVAR_PLANO_USO_EMBUTIDO = config(
    "VENDA_ERP_PEDIDOS_SALVAR_PLANO_USO_EMBUTIDO", default=False, cast=bool
)
# HTTP 200 + erro de plano: se o 1º POST não era embutido, tenta objeto { Id, Nome }.
VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_ANINHADO = config(
    "VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_ANINHADO", default=True, cast=bool
)
# Opcional: variantes que removem plano do cabeçalho / texto nas linhas (só se "localizar" no retorno).
VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_ALTERNATIVAS = config(
    "VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_ALTERNATIVAS", default=False, cast=bool
)
# "Localizar plano": reenvia com outros textos (Nome só, Hierarquia, hífen, PlanoDeConta de um lançamento, etc.).
VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_TEXTO_VARIANTES = config(
    "VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_TEXTO_VARIANTES", default=True, cast=bool
)
# Depois das variantes de texto: tenta ``planoDeConta`` como objeto estilo PlanoDeContaRetornoBusca (nome, codigoNatureza, …).
VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_OBJETO_RETORNO_BUSCA = config(
    "VENDA_ERP_PEDIDOS_SALVAR_RETRY_PLANO_OBJETO_RETORNO_BUSCA", default=True, cast=bool
)
# Ao gravar venda no PDV: baixa quantidades no estoque visto pelo Agro (AjusteRapidoEstoque + saldo ERP Mongo).
PDV_BAIXA_ESTOQUE_AGRO_NA_VENDA = config("PDV_BAIXA_ESTOQUE_AGRO_NA_VENDA", default=True, cast=bool)
# Depósito da baixa: centro | vila (mesma convenção do PIN / entrada NF).
PDV_VENDA_ESTOQUE_DEPOSITO = config("PDV_VENDA_ESTOQUE_DEPOSITO", default="centro").strip().lower() or "centro"
PDV_WIZARD_SALDO_VALE_CREDITO = config("PDV_WIZARD_SALDO_VALE_CREDITO", default="0").strip()
PDV_WIZARD_SALDO_CASHBACK = config("PDV_WIZARD_SALDO_CASHBACK", default="0").strip()
# WhatsApp após impressão de cupom de transferência (Vila Elias). Vazio = usa PDV_ENTREGA_WHATSAPP.
TRANSFERENCIA_WHATSAPP = config('TRANSFERENCIA_WHATSAPP', default='').strip()
# Token para endpoint HTTP do cron de alertas (sem shell). Mantenha forte e secreto.
ALERTA_VENDAS_CRON_TOKEN = config('ALERTA_VENDAS_CRON_TOKEN', default='').strip()
# Se True, só envia perto da hora cheia (00..tol minutos). Se False, envia 1x por hora em qualquer minuto.
ALERTA_VENDAS_HORA_CHEIA_ESTRITO = config('ALERTA_VENDAS_HORA_CHEIA_ESTRITO', default=False, cast=bool)
# Quando estrito=True, tolerância de atraso do scheduler em minutos (0..15).
ALERTA_VENDAS_HORA_CHEIA_TOL_MIN = config('ALERTA_VENDAS_HORA_CHEIA_TOL_MIN', default=5, cast=int)
# --- Rotas Google Maps (painel de entregas): duas lojas ---
# Links “pin” no Maps (abrir a loja no navegador). Podem ser sobrescritos no .env.
_LOJA_MAPS_LINK_CENTRO_DEFAULT = (
    "https://www.google.com/maps/dir/GM+AGRO+MAIS,+Av.+Adhemar+de+Barros,+230+-+Centro,+Jacupiranga+-+SP,+11940-000//@-24.6939187,-48.00301,53m/data=!3m1!1e3!4m8!4m7!1m5!1m1!1s0x94dad7ad67522a83:0x6bc5a31e953afdd7!2m2!1d-48.0030368!2d-24.6939103!1m0?entry=ttu&g_ep=EgoyMDI2MDMyNC4wIKXMDSoASAFQAw%3D%3D"
)
_LOJA_MAPS_LINK_VILA_DEFAULT = (
    "https://www.google.com/maps/dir/-24.7022751,-48.0029425//@-24.7022767,-48.0028979,47m/data=!3m1!1e3?entry=ttu&g_ep=EgoyMDI2MDMyNC4wIKXMDSoASAFQAw%3D%3D"
)
# Texto ou "lat,lng" usado como origem em maps/dir (API). Coordenadas tiradas dos links acima.
LOJA_MAPS_LINK_CENTRO = config("LOJA_MAPS_LINK_CENTRO", default=_LOJA_MAPS_LINK_CENTRO_DEFAULT).strip()
LOJA_MAPS_LINK_VILA = config("LOJA_MAPS_LINK_VILA", default=_LOJA_MAPS_LINK_VILA_DEFAULT).strip()

_legacy_loja_maps = config("LOJA_MAPS_ORIGEM_TEXTO", default="").strip()
LOJA_MAPS_ORIGEM_CENTRO = (
    config("LOJA_MAPS_ORIGEM_CENTRO", default="").strip()
    or _legacy_loja_maps
    or "-24.6939103,-48.0030368"
)
LOJA_MAPS_ORIGEM_VILA = config("LOJA_MAPS_ORIGEM_VILA", default="").strip() or "-24.7022751,-48.0029425"
# Legado: se você só definia uma origem, ela vira fallback do Centro (acima).
LOJA_MAPS_ORIGEM_TEXTO = _legacy_loja_maps