"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
DEBUG = True
import dj_database_url
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
    "https://agro-consulta.onrender.com",
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'base',

    'rest_framework',

    
    'lojas',
    'produtos',
    'estoque',
    'transferencias',
    'relatorios',
    'integracoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'config.urls'
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#sadasdas#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'base' / 'templates'], # Caminho absoluto para a pasta que você criou
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
VENDA_ERP_MONGO_URL = config('VENDA_ERP_MONGO_URL', default='')
VENDA_ERP_MONGO_DB = config('VENDA_ERP_MONGO_DB', default='')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'agro-consulta-cache',
    }
}

CONSULTA_CACHE_TTL = 20
# Configurações da API Venda ERP
VENDA_ERP_API_BASE_URL = config('VENDA_ERP_API_BASE_URL', default='https://cw.vendaerp.com.br')
VENDA_ERP_API_TOKEN = config('VENDA_ERP_API_TOKEN', default='')
# Financeiro: sufixo após /api/request/ (ex.: Lancamentos/SalvarBaixa). Vazio = não chama API.
VENDA_ERP_API_FINANCEIRO_BAIXA_PATH = config('VENDA_ERP_API_FINANCEIRO_BAIXA_PATH', default='').strip()
VENDA_ERP_API_FINANCEIRO_LANCAMENTO_PATH = config('VENDA_ERP_API_FINANCEIRO_LANCAMENTO_PATH', default='').strip()

# PDV: WhatsApp para aviso de separação/entrega ao salvar orçamento (somente dígitos, ex.: 5513999999999).
# wa.me abre conversa com um número; não existe URL oficial para “postar” direto em grupo pelo navegador.
# Para grupo: API (ex. WhatsApp Business), ou número da loja que repassa no grupo manualmente.
PDV_ENTREGA_WHATSAPP = config('PDV_ENTREGA_WHATSAPP', default='5513997673389').strip()
# WhatsApp após impressão de cupom de transferência (Vila Elias). Vazio = usa PDV_ENTREGA_WHATSAPP.
TRANSFERENCIA_WHATSAPP = config('TRANSFERENCIA_WHATSAPP', default='').strip()
# Token para endpoint HTTP do cron de alertas (sem shell). Mantenha forte e secreto.
ALERTA_VENDAS_CRON_TOKEN = config('ALERTA_VENDAS_CRON_TOKEN', default='').strip()
# --- Rotas Google Maps (painel de entregas): duas lojas ---
# Links “pin” no Maps (abrir a loja no navegador). Podem ser sobrescritos no .env.
_LOJA_MAPS_LINK_CENTRO_DEFAULT = (
    "https://www.google.com/maps/dir/GM+AGRO+MAIS,+Av.+Adhemar+de+Barros,+230+-+Centro,+Jacupiranga+-+SP,+11940-000//@-24.6939187,-48.00301,53m/data=!3m1!1e3!4m8!4m7!1m5!1m1!1s0x94dad7ad67522a83:0x6bc5a31e953afdd7!2m2!1d-48.0030368!2d-24.6939103!1m0?entry=ttu&g_ep=EgoyMDI2MDMyNC4wIKXMDSoASAFQAw%3D%3D"
)
_LOJA_MAPS_LINK_VILA_DEFAULT = (
    "https://www.google.com/maps/dir/-24.7022751,-48.0029425//@-24.7022767,-48.0028979,47m/data=!3m1!1e3?entry=ttu&g_ep=EgoyMDI2MDMyNC4wIKXMDSoASAFQAw%3D%3D"
)
# Texto ou "lat,lng" usado como origem em maps/dir (API). Coordenadas tiradas dos links acima.
LOJA_MAPS_LINK_CENTRO = config("LOJA_MAPS_LINK_CENTRO", default=_LOJA_MAPS_LINK_CENTRO_DEFAULT).strip()
LOJA_MAPS_LINK_VILA = config("LOJA_MAPS_LINK_VILA", default=_LOJA_MAPS_LINK_VILA_DEFAULT).strip()

_legacy_loja_maps = config("LOJA_MAPS_ORIGEM_TEXTO", default="").strip()
LOJA_MAPS_ORIGEM_CENTRO = (
    config("LOJA_MAPS_ORIGEM_CENTRO", default="").strip()
    or _legacy_loja_maps
    or "-24.6939103,-48.0030368"
)
LOJA_MAPS_ORIGEM_VILA = config("LOJA_MAPS_ORIGEM_VILA", default="").strip() or "-24.7022751,-48.0029425"
# Legado: se você só definia uma origem, ela vira fallback do Centro (acima).
LOJA_MAPS_ORIGEM_TEXTO = _legacy_loja_maps