# Lista de bairros (Jacupiranga) — alinhada ao painel `entregas_painel.html` para o PDV Wizard.

BAIRROS_JACUPI_URBANOS = [
    "Barro Branco",
    "Botujuru / Botuquara",
    "Centro",
    "Cidade Nova",
    "Distrito Industrial",
    "Flor da Vila",
    "Jardim Brasília",
    "Jardim Primavera",
    "Lençol",
    "Morangaba",
    "Novo Botujuru",
    "Padre André I",
    "Padre André II",
    "Vila Elias",
    "Vila Josefa",
    "Vila Vital",
]

BAIRROS_JACUPI_RURAIS = [
    "Água Parada",
    "Areiado",
    "Banana",
    "Barbosinha",
    "Barra do Pindaúba",
    "Barra do Rio Canha",
    "Barra do Soldado",
    "Barracão",
    "Biquinha",
    "Bulha",
    "Cachoeirinha",
    "Canha",
    "Carravieri",
    "Cipriano",
    "Coroado",
    "Engenheiro Velho",
    "Guaracuí",
    "Guaramiranga",
    "Guaraú",
    "Lageado",
    "Manuel Gomes",
    "Nhunguvira",
    "Pedreira",
    "Pedreira Jorcal",
    "Pindaúba",
    "Pinheiros",
    "Poça",
    "Riachão",
    "Ribeirão da Batata",
    "Rosali",
    "Seringal",
    "Serrote",
    "Tábua",
    "Tarciso",
]
