# Lista de bairros (Jacupiranga) — alinhada ao painel `entregas_painel.html` para o PDV Wizard.

BAIRROS_JACUPI_URBANOS = [
    "Barro Branco",
    "Botujuru / Botuquara",
    "Centro",
    "Cidade Nova",
    "Distrito Industrial",
    "Flor da Vila",
    "Jardim Brasília",
    "Jardim Primavera",
    "Lençol",
    "Morangaba",
    "Novo Botujuru",
    "Padre André I",
    "Padre André II",
    "Vila Elias",
    "Vila Josefa",
    "Vila Vital",
]

BAIRROS_JACUPI_RURAIS = [
    "Água Parada",
    "Areiado",
    "Banana",
    "Barbosinha",
    "Barra do Pindaúba",
    "Barra do Rio Canha",
    "Barra do Soldado",
    "Barracão",
    "Biquinha",
    "Bulha",
    "Cachoeirinha",
    "Canha",
    "Carravieri",
    "Cipriano",
    "Coroado",
    "Engenheiro Velho",
    "Guaracuí",
    "Guaramiranga",
    "Guaraú",
    "Lageado",
    "Manuel Gomes",
    "Nhunguvira",
    "Pedreira",
    "Pedreira Jorcal",
    "Pindaúba",
    "Pinheiros",
    "Poça",
    "Riachão",
    "Ribeirão da Batata",
    "Rosali",
    "Seringal",
    "Serrote",
    "Tábua",
    "Tarciso",
]

# Padrões Jacupiranga — alinhados a `entregas_painel.html` (EDLOC_*).
JACUPIRANGA_CEP_PADRAO = "11940-000"
JACUPIRANGA_CENTRO_REF_LL = (-24.6939103, -48.0030368)
# Trechos de logradouro no Centro (normalizar acento/caixa antes de comparar).
JACUPIRANGA_LOGRADOUROS_CENTRO = (
    "ademar de barros",
    "adhemar de barros",
    "rui barbosa",
    "quatro de junho",
    "7 de setembro",
    "sete de setembro",
    "sao paulo",
    "nove de julho",
    "jose bonifacio",
    "joao pessoa",
    "coronel jose gladiador",
    "prefeito artur jose",
)
