from django.urls import path
from . import views

urlpatterns = [
    # --- PÁGINAS ---
    path('', views.consulta_produtos, name='consulta_produtos'),
    path('historico/', views.historico_ajustes, name='historico_ajustes'),
    path('transferencias/', views.sugestao_transferencia, name='sugestao_transferencia'),
    path('entregas/', views.entregas_painel_view, name='entregas_painel'),
    path('entregas/api/registrar/', views.api_entrega_registrar, name='api_entrega_registrar'),
    path('entregas/api/listar/', views.api_entregas_listar, name='api_entregas_listar'),
    path('entregas/api/atualizar/', views.api_entrega_atualizar, name='api_entrega_atualizar'),
    path(
        'entregas/api/ordenar-rota/',
        views.api_entregas_ordenar_rota,
        name='api_entregas_ordenar_rota',
    ),
    path('ajuste-mobile/', views.ajuste_mobile_view, name='ajuste_mobile'), # <-- A rota que faltava
    path('compras/', views.compras_view, name='compras_view'),
    path(
        'entrada-nota/',
        views.entrada_nota_view,
        name='entrada_nota',
    ),
    path(
        'lancamentos/',
        views.lancamentos_financeiros_view,
        name='lancamentos_financeiros',
    ),
    path(
        'financeiro/resumo-gerencial/',
        views.resumo_financeiro_gerencial_view,
        name='resumo_financeiro_gerencial',
    ),
    path(
        'lancamentos/dre/',
        views.lancamentos_dre_view,
        name='lancamentos_dre',
    ),
    path(
        'lancamentos/contas-pagar/',
        views.lancamentos_contas_pagar_view,
        name='lancamentos_contas_pagar',
    ),
    path(
        'lancamentos/novo-manual/',
        views.lancamentos_manual_view,
        name='lancamentos_manual',
    ),
    path(
        'lancamentos/fluxo-calendario/',
        views.lancamentos_fluxo_calendario_view,
        name='lancamentos_fluxo_calendario',
    ),
    path('pdv/checkout/', views.pdv_checkout, name='pdv_checkout'),
    path('vendas/exportar-csv/', views.vendas_exportar_csv, name='vendas_exportar_csv'),
    path('vendas/', views.vendas_lista, name='vendas_lista'),
    path('vendas-hoje/', views.vendas_hoje_redirect, name='vendas_hoje'),
    path('venda/<int:pk>/', views.venda_agro_detalhe, name='venda_agro_detalhe'),
    path('clientes/', views.clientes_lista, name='clientes_lista'),
    path('clientes/sincronizar/', views.clientes_sincronizar, name='clientes_sincronizar'),
    path('clientes/novo/', views.cliente_novo, name='cliente_novo'),
    path('clientes/<int:pk>/editar/', views.cliente_editar, name='cliente_editar'),
    path('rh/', views.rh_painel, name='rh_painel'),
    path('caixa/', views.caixa_painel, name='caixa_painel'),
    path('caixa/saida/', views.caixa_saida_view, name='caixa_saida'),
    path('caixa/abrir/', views.caixa_abrir, name='caixa_abrir'),
    path('caixa/fechar/', views.caixa_fechar, name='caixa_fechar'),

    # --- APIs ---
    path('api/login-mobile/', views.api_login_mobile, name='api_login_mobile'),
    path('api/buscar/', views.api_buscar_produtos, name='api_buscar_mobile'),
    path('api/buscar-compras/', views.api_buscar_compras, name='api_buscar_compras'),
    path('api/lancamentos/', views.api_lancamentos_lista, name='api_lancamentos_lista'),
    path(
        'api/lancamentos/export-csv/',
        views.api_lancamentos_export_csv,
        name='api_lancamentos_export_csv',
    ),
    path(
        'api/lancamentos/opcoes-baixa/',
        views.api_lancamentos_opcoes_baixa,
        name='api_lancamentos_opcoes_baixa',
    ),
    path(
        'api/lancamentos/opcoes-baixa/extra/',
        views.api_lancamentos_opcoes_baixa_extra_criar,
        name='api_lancamentos_opcoes_baixa_extra_criar',
    ),
    path(
        'api/lancamentos/opcoes-baixa/extra/<int:pk>/excluir/',
        views.api_lancamentos_opcoes_baixa_extra_excluir,
        name='api_lancamentos_opcoes_baixa_extra_excluir',
    ),
    path(
        'api/lancamentos/baixa/',
        views.api_lancamentos_baixa,
        name='api_lancamentos_baixa',
    ),
    path(
        'api/lancamentos/baixa-parcial/',
        views.api_lancamentos_baixa_parcial,
        name='api_lancamentos_baixa_parcial',
    ),
    path(
        'api/lancamentos/alterar/',
        views.api_lancamentos_alterar,
        name='api_lancamentos_alterar',
    ),
    path(
        'api/lancamentos/excluir/',
        views.api_lancamentos_excluir,
        name='api_lancamentos_excluir',
    ),
    path(
        'api/lancamentos/saida-caixa/',
        views.api_lancamentos_saida_caixa,
        name='api_lancamentos_saida_caixa',
    ),
    path(
        'api/lancamentos/dre-resumo/',
        views.api_lancamentos_dre_resumo,
        name='api_lancamentos_dre_resumo',
    ),
    path(
        'api/lancamentos/sugestoes/',
        views.api_lancamentos_sugestoes,
        name='api_lancamentos_sugestoes',
    ),
    path(
        'api/lancamentos/criar-manual-lote/',
        views.api_lancamentos_criar_manual_lote,
        name='api_lancamentos_criar_manual_lote',
    ),
    path(
        'api/lancamentos/planos-distintos/',
        views.api_lancamentos_planos_distintos,
        name='api_lancamentos_planos_distintos',
    ),
    path(
        'api/lancamentos/fluxo-calendario/',
        views.api_lancamentos_fluxo_calendario,
        name='api_lancamentos_fluxo_calendario',
    ),
    path(
        'api/lancamentos/contas-pagar/',
        views.api_lancamentos_contas_pagar,
        name='api_lancamentos_contas_pagar',
    ),
    path('api/ajustar/', views.api_ajustar_estoque, name='api_ajustar_estoque'),
    path('api/todos-produtos/', views.api_todos_produtos_local, name='api_todos_produtos_local'),
    path('api/todos-produtos/delta/', views.api_todos_produtos_delta, name='api_todos_produtos_delta'),
    path('api/pdv/saldos/', views.api_pdv_saldos_compacto, name='api_pdv_saldos'),
    path('api/pdv/metricas-produtos/', views.api_pdv_metricas_produtos, name='api_pdv_metricas_produtos'),
    path('api/pdv/top-vendidos/', views.api_pdv_top_vendidos, name='api_pdv_top_vendidos'),
    path('api/pdv/invalidar-catalogo/', views.api_pdv_invalidar_cache_catalogo, name='api_pdv_invalidar_catalogo'),
    path('api/cron/enviar-alerta-vendas-dia/', views.api_cron_enviar_alerta_vendas_dia, name='api_cron_enviar_alerta_vendas_dia'),
    path('api/autocomplete/', views.api_autocomplete_produtos, name='api_autocomplete_produtos'),
    path('api/buscar-clientes/', views.api_buscar_clientes, name='api_buscar_clientes'),
    path('api/listar-clientes/', views.api_list_customers, name='api_list_customers'),
    path('api/enviar-pedido-erp/', views.api_enviar_pedido_erp, name='api_enviar_pedido_erp'),
    path('api/pdv/checkout-draft/', views.api_pdv_salvar_checkout_draft, name='api_pdv_salvar_checkout_draft'),
    path('api/pdv/checkout-draft/clear/', views.api_pdv_limpar_checkout_draft, name='api_pdv_limpar_checkout_draft'),
    path('api/buscar-produto-id/<str:id>/', views.api_buscar_produto_id, name='api_buscar_produto_id'),
    path(
        'api/entrada-nota/sefaz-status/',
        views.api_entrada_nota_sefaz_status,
        name='api_entrada_nota_sefaz_status',
    ),
    path(
        'api/entrada-nota/parse-xml/',
        views.api_entrada_nota_parse_xml,
        name='api_entrada_nota_parse_xml',
    ),
    path(
        'api/entrada-nota/salvar/',
        views.api_entrada_nota_salvar,
        name='api_entrada_nota_salvar',
    ),
    path(
        'api/entrada-nota/rascunhos/',
        views.api_entrada_nota_rascunhos,
        name='api_entrada_nota_rascunhos',
    ),
    path(
        'api/entrada-nota/fornecedores/',
        views.api_entrada_nota_fornecedores,
        name='api_entrada_nota_fornecedores',
    ),
    path(
        'api/entrada-nota/financeiro/',
        views.api_entrada_nota_financeiro,
        name='api_entrada_nota_financeiro',
    ),
    path(
        'api/entrada-nota/estoque-agro/',
        views.api_entrada_nota_estoque_agro,
        name='api_entrada_nota_estoque_agro',
    ),
    path(
        'api/entrada-nota/dist-dfe/',
        views.api_entrada_nota_dist_dfe,
        name='api_entrada_nota_dist_dfe',
    ),
]