from django.urls import include, path
from . import views, views_mp_point

urlpatterns = [
    # --- PÁGINAS ---
    path('', views.home, name='home'),
    path('consulta/', views.consulta_produtos, name='consulta_produtos'),
    path('historico/', views.historico_ajustes, name='historico_ajustes'),
    path('transferencias/', views.sugestao_transferencia, name='sugestao_transferencia'),
    path('entregas/', views.entregas_painel_view, name='entregas_painel'),
    path('entregas/api/registrar/', views.api_entrega_registrar, name='api_entrega_registrar'),
    path('entregas/api/listar/', views.api_entregas_listar, name='api_entregas_listar'),
    path('entregas/api/atualizar/', views.api_entrega_atualizar, name='api_entrega_atualizar'),
    path(
        'entregas/api/ordenar-rota/',
        views.api_entregas_ordenar_rota,
        name='api_entregas_ordenar_rota',
    ),
    path('ajuste-mobile/', views.ajuste_mobile_view, name='ajuste_mobile'), # <-- A rota que faltava
    path('compras/', views.compras_view, name='compras_view'),
    path(
        'produtos/cadastro-erp/',
        views.produtos_cadastro_erp_view,
        name='produtos_cadastro_erp',
    ),
    path('produtos/gestao/', views.produtos_gestao_view, name='produtos_gestao'),
    path(
        'entrada-nota/',
        views.entrada_nota_view,
        name='entrada_nota',
    ),
    path(
        'lancamentos/',
        views.lancamentos_financeiros_view,
        name='lancamentos_financeiros',
    ),
    path(
        'financeiro/resumo-gerencial/',
        views.resumo_financeiro_gerencial_view,
        name='resumo_financeiro_gerencial',
    ),
    path(
        'lancamentos/dre/',
        views.lancamentos_dre_view,
        name='lancamentos_dre',
    ),
    path(
        'lancamentos/contas-pagar/',
        views.lancamentos_contas_pagar_view,
        name='lancamentos_contas_pagar',
    ),
    path(
        'lancamentos/contas-receber/',
        views.lancamentos_contas_receber_view,
        name='lancamentos_contas_receber',
    ),
    path(
        'lancamentos/novo-manual/',
        views.lancamentos_manual_view,
        name='lancamentos_manual',
    ),
    path(
        'emprestimos/',
        views.emprestimos_gestao_view,
        name='emprestimos_gestao',
    ),
    path(
        'emprestimos/externo/',
        views.emprestimos_externo_view,
        name='emprestimos_externo',
    ),
    path(
        'emprestimos/interno/',
        views.emprestimos_interno_view,
        name='emprestimos_interno',
    ),
    path(
        'emprestimos/consulta/',
        views.emprestimos_consulta_view,
        name='emprestimos_consulta',
    ),
    path(
        'lancamentos/fluxo-calendario/',
        views.lancamentos_fluxo_calendario_view,
        name='lancamentos_fluxo_calendario',
    ),
    path('estoque/sincronizacao/', views.estoque_sincronizacao_view, name='estoque_sincronizacao'),
    path('pdv/checkout/', views.pdv_checkout, name='pdv_checkout'),
    path('vendas/exportar-csv/', views.vendas_exportar_csv, name='vendas_exportar_csv'),
    path('vendas/', views.vendas_lista, name='vendas_lista'),
    path('vendas-hoje/', views.vendas_hoje_redirect, name='vendas_hoje'),
    path(
        'venda/<int:pk>/reenviar-erp/',
        views.api_venda_agro_reenviar_erp,
        name='api_venda_agro_reenviar_erp',
    ),
    path('venda/<int:pk>/', views.venda_agro_detalhe, name='venda_agro_detalhe'),
    path('clientes/', views.clientes_lista, name='clientes_lista'),
    path('clientes/sincronizar/', views.clientes_sincronizar, name='clientes_sincronizar'),
    path('clientes/novo/', views.cliente_novo, name='cliente_novo'),
    path('clientes/<int:pk>/editar/', views.cliente_editar, name='cliente_editar'),
    path('rh/', include('rh.urls')),
    path('caixa/', views.caixa_painel, name='caixa_painel'),
    path('caixa/saida/', views.caixa_saida_view, name='caixa_saida'),
    path('caixa/abrir/', views.caixa_abrir, name='caixa_abrir'),
    path('caixa/fechar/', views.caixa_fechar, name='caixa_fechar'),

    # --- APIs ---
    path('api/login-mobile/', views.api_login_mobile, name='api_login_mobile'),
    path('api/produtos/cadastro/', views.api_produtos_cadastro, name='api_produtos_cadastro'),
    path('api/produtos/gestao/lista/', views.api_produtos_gestao_lista, name='api_produtos_gestao_lista'),
    path('api/produtos/gestao/facetas/', views.api_produtos_gestao_facetas, name='api_produtos_gestao_facetas'),
    path(
        'api/produtos/gestao/ajuste-estoque/',
        views.api_produtos_gestao_ajuste_estoque,
        name='api_produtos_gestao_ajuste_estoque',
    ),
    path(
        'api/produtos/gestao/overlay/',
        views.api_produtos_gestao_overlay_salvar,
        name='api_produtos_gestao_overlay_salvar',
    ),
    path(
        'api/produtos/cadastro/detalhe/<str:produto_id>/',
        views.api_produtos_cadastro_detalhe,
        name='api_produtos_cadastro_detalhe',
    ),
    path('api/produtos/grupos/', views.api_produtos_grupos_listar, name='api_produtos_grupos_listar'),
    path('api/produtos/grupos/salvar/', views.api_produtos_grupo_salvar, name='api_produtos_grupo_salvar'),
    path('api/produtos/grupos/<int:pk>/', views.api_produtos_grupo_obter, name='api_produtos_grupo_obter'),
    path(
        'api/produtos/grupos/<int:pk>/excluir/',
        views.api_produtos_grupo_excluir,
        name='api_produtos_grupo_excluir',
    ),
    path('api/buscar/', views.api_buscar_produtos, name='api_buscar_mobile'),
    path('api/buscar-compras/', views.api_buscar_compras, name='api_buscar_compras'),
    path('api/lancamentos/', views.api_lancamentos_lista, name='api_lancamentos_lista'),
    path(
        'api/lancamentos/export-csv/',
        views.api_lancamentos_export_csv,
        name='api_lancamentos_export_csv',
    ),
    path(
        'api/lancamentos/export-financeiro-xlsx/',
        views.api_lancamentos_export_financeiro_xlsx,
        name='api_lancamentos_export_financeiro_xlsx',
    ),
    path(
        'api/lancamentos/export-financeiro-pdf/',
        views.api_lancamentos_export_financeiro_pdf,
        name='api_lancamentos_export_financeiro_pdf',
    ),
    path(
        'api/lancamentos/opcoes-baixa/',
        views.api_lancamentos_opcoes_baixa,
        name='api_lancamentos_opcoes_baixa',
    ),
    path(
        'api/lancamentos/opcoes-baixa/extra/',
        views.api_lancamentos_opcoes_baixa_extra_criar,
        name='api_lancamentos_opcoes_baixa_extra_criar',
    ),
    path(
        'api/lancamentos/opcoes-baixa/extra/<int:pk>/excluir/',
        views.api_lancamentos_opcoes_baixa_extra_excluir,
        name='api_lancamentos_opcoes_baixa_extra_excluir',
    ),
    path(
        'api/lancamentos/baixa/',
        views.api_lancamentos_baixa,
        name='api_lancamentos_baixa',
    ),
    path(
        'api/lancamentos/baixa-parcial/',
        views.api_lancamentos_baixa_parcial,
        name='api_lancamentos_baixa_parcial',
    ),
    path(
        'api/lancamentos/alterar/',
        views.api_lancamentos_alterar,
        name='api_lancamentos_alterar',
    ),
    path(
        'api/lancamentos/excluir/',
        views.api_lancamentos_excluir,
        name='api_lancamentos_excluir',
    ),
    path(
        'api/lancamentos/saida-caixa/',
        views.api_lancamentos_saida_caixa,
        name='api_lancamentos_saida_caixa',
    ),
    path(
        'api/lancamentos/dre-resumo/',
        views.api_lancamentos_dre_resumo,
        name='api_lancamentos_dre_resumo',
    ),
    path(
        'api/lancamentos/sugestoes/',
        views.api_lancamentos_sugestoes,
        name='api_lancamentos_sugestoes',
    ),
    path(
        'api/lancamentos/criar-manual-lote/',
        views.api_lancamentos_criar_manual_lote,
        name='api_lancamentos_criar_manual_lote',
    ),
    path(
        'api/emprestimos/listar/',
        views.api_emprestimos_listar,
        name='api_emprestimos_listar',
    ),
    path(
        'api/emprestimos/criar/',
        views.api_emprestimos_criar,
        name='api_emprestimos_criar',
    ),
    path(
        'api/emprestimos/interno-pagamento/',
        views.api_emprestimos_interno_pagamento,
        name='api_emprestimos_interno_pagamento',
    ),
    path(
        'api/emprestimos/defaults/',
        views.api_emprestimos_defaults,
        name='api_emprestimos_defaults',
    ),
    path(
        'api/emprestimos/erp-lancamentos/',
        views.api_emprestimos_erp_lancamentos,
        name='api_emprestimos_erp_lancamentos',
    ),
    path(
        'api/lancamentos/planos-distintos/',
        views.api_lancamentos_planos_distintos,
        name='api_lancamentos_planos_distintos',
    ),
    path(
        'api/lancamentos/atalhos-filtro/',
        views.api_lancamentos_atalhos_filtro,
        name='api_lancamentos_atalhos_filtro',
    ),
    path(
        'api/lancamentos/fluxo-calendario/',
        views.api_lancamentos_fluxo_calendario,
        name='api_lancamentos_fluxo_calendario',
    ),
    path(
        'api/lancamentos/contas-pagar/',
        views.api_lancamentos_contas_pagar,
        name='api_lancamentos_contas_pagar',
    ),
    path('api/ajustar/', views.api_ajustar_estoque, name='api_ajustar_estoque'),
    path('api/todos-produtos/', views.api_todos_produtos_local, name='api_todos_produtos_local'),
    path('api/todos-produtos/delta/', views.api_todos_produtos_delta, name='api_todos_produtos_delta'),
    path('api/pdv/saldos/', views.api_pdv_saldos_compacto, name='api_pdv_saldos'),
    path('api/pdv/metricas-produtos/', views.api_pdv_metricas_produtos, name='api_pdv_metricas_produtos'),
    path('api/pdv/top-vendidos/', views.api_pdv_top_vendidos, name='api_pdv_top_vendidos'),
    path('api/pdv/invalidar-catalogo/', views.api_pdv_invalidar_cache_catalogo, name='api_pdv_invalidar_catalogo'),
    path('api/cron/enviar-alerta-vendas-dia/', views.api_cron_enviar_alerta_vendas_dia, name='api_cron_enviar_alerta_vendas_dia'),
    path('api/cron/estoque-mongo-ping/', views.api_cron_estoque_mongo_ping, name='api_cron_estoque_mongo_ping'),
    path('api/autocomplete/', views.api_autocomplete_produtos, name='api_autocomplete_produtos'),
    path('api/buscar-clientes/', views.api_buscar_clientes, name='api_buscar_clientes'),
    path('api/listar-clientes/', views.api_list_customers, name='api_list_customers'),
    path('api/enviar-pedido-erp/', views.api_enviar_pedido_erp, name='api_enviar_pedido_erp'),
    path('api/pdv/cliente-rapido/', views.api_pdv_cliente_rapido, name='api_pdv_cliente_rapido'),
    path('api/pdv/checkout-draft/', views.api_pdv_salvar_checkout_draft, name='api_pdv_salvar_checkout_draft'),
    path('api/pdv/checkout-draft/clear/', views.api_pdv_limpar_checkout_draft, name='api_pdv_limpar_checkout_draft'),
    path(
        'api/pdv/mp-point/criar/',
        views_mp_point.api_pdv_mp_point_criar,
        name='api_pdv_mp_point_criar',
    ),
    path(
        'api/pdv/mp-point/status/',
        views_mp_point.api_pdv_mp_point_status,
        name='api_pdv_mp_point_status',
    ),
    path(
        'api/pdv/mp-point/finalizar/',
        views_mp_point.api_pdv_mp_point_finalizar,
        name='api_pdv_mp_point_finalizar',
    ),
    path(
        'api/pdv/mp-point/abandonar/',
        views_mp_point.api_pdv_mp_point_abandon,
        name='api_pdv_mp_point_abandon',
    ),
    path('api/buscar-produto-id/<str:id>/', views.api_buscar_produto_id, name='api_buscar_produto_id'),
    path(
        'api/entrada-nota/sefaz-status/',
        views.api_entrada_nota_sefaz_status,
        name='api_entrada_nota_sefaz_status',
    ),
    path(
        'api/entrada-nota/parse-xml/',
        views.api_entrada_nota_parse_xml,
        name='api_entrada_nota_parse_xml',
    ),
    path(
        'api/entrada-nota/salvar/',
        views.api_entrada_nota_salvar,
        name='api_entrada_nota_salvar',
    ),
    path(
        'api/entrada-nota/rascunhos/',
        views.api_entrada_nota_rascunhos,
        name='api_entrada_nota_rascunhos',
    ),
    path(
        'api/entrada-nota/rascunho/',
        views.api_entrada_nota_rascunho_obter,
        name='api_entrada_nota_rascunho_obter',
    ),
    path(
        'api/entrada-nota/rascunho/excluir/',
        views.api_entrada_nota_rascunho_excluir,
        name='api_entrada_nota_rascunho_excluir',
    ),
    path(
        'api/entrada-nota/rascunho/atualizar/',
        views.api_entrada_nota_rascunho_atualizar,
        name='api_entrada_nota_rascunho_atualizar',
    ),
    path(
        'api/entrada-nota/rascunho/acao/',
        views.api_entrada_nota_rascunho_acao,
        name='api_entrada_nota_rascunho_acao',
    ),
    path(
        'api/entrada-nota/fornecedores/',
        views.api_entrada_nota_fornecedores,
        name='api_entrada_nota_fornecedores',
    ),
    path(
        'api/entrada-nota/financeiro/',
        views.api_entrada_nota_financeiro,
        name='api_entrada_nota_financeiro',
    ),
    path(
        'api/entrada-nota/estoque-agro/',
        views.api_entrada_nota_estoque_agro,
        name='api_entrada_nota_estoque_agro',
    ),
    path(
        'api/entrada-nota/dist-dfe/',
        views.api_entrada_nota_dist_dfe,
        name='api_entrada_nota_dist_dfe',
    ),
]