# Generated by Django 6.0.3 on 2026-04-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_integracao_pedido_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa_pai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_como_pai', to='base.empresa')),
            ],
            options={
                'verbose_name': 'Grupo Empresarial',
                'verbose_name_plural': 'Grupos Empresariais',
                'db_table': 'grupo_empresarial',
            },
        ),
        migrations.CreateModel(
            name='GrupoEmpresarialEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAI', 'Pai'), ('FILHA', 'Filha'), ('COLIGADA', 'Coligada')], default='FILHA', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_vinculados', to='base.empresa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to='financeiro.grupoempresarial')),
            ],
            options={
                'db_table': 'grupo_empresarial_empresa',
                'indexes': [models.Index(fields=['grupo', 'empresa'], name='grupo_empre_grupo_i_d5ded4_idx'), models.Index(fields=['empresa', 'ativo'], name='grupo_empre_empresa_71387b_idx')],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'empresa'), name='uniq_grupo_empresarial_empresa')],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_competencia', models.DateField(db_index=True)),
                ('data_movimento', models.DateField(db_index=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('natureza', models.CharField(choices=[('RECEITA_OPERACIONAL', 'Receita Operacional'), ('RECEITA_NAO_OPERACIONAL', 'Receita Não Operacional'), ('CMV', 'CMV'), ('DESPESA_FIXA', 'Despesa Fixa'), ('DESPESA_VARIAVEL', 'Despesa Variável'), ('DESPESA_FINANCEIRA', 'Despesa Financeira'), ('EMPRESTIMO_ENTRADA', 'Entrada de Empréstimo'), ('EMPRESTIMO_AMORTIZACAO', 'Amortização de Empréstimo'), ('TRANSFERENCIA_INTERNA', 'Transferência Interna'), ('APORTE_SOCIO', 'Aporte de Sócio'), ('RETIRADA_SOCIO', 'Retirada de Sócio')], db_index=True, max_length=40)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('VENDA_ERP', 'Venda ERP'), ('COMPRA_ERP', 'Compra ERP'), ('TRANSFERENCIA_ERP', 'Transferência ERP'), ('CONCILIACAO', 'Conciliação')], default='MANUAL', max_length=30)),
                ('plano_conta_codigo', models.CharField(blank=True, default='', max_length=50)),
                ('plano_conta_descricao', models.CharField(blank=True, default='', max_length=255)),
                ('documento_ref', models.CharField(blank=True, default='', max_length=120)),
                ('grupo_ref', models.CharField(blank=True, default='', max_length=120)),
                ('eh_interno_grupo', models.BooleanField(db_index=True, default=False)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.empresa')),
                ('empresa_contraparte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_como_contraparte', to='base.empresa')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.loja')),
            ],
            options={
                'db_table': 'lancamento_financeiro',
                'indexes': [models.Index(fields=['empresa', 'data_competencia'], name='lancamento__empresa_4c176a_idx'), models.Index(fields=['empresa', 'natureza', 'data_competencia'], name='lancamento__empresa_d40c11_idx'), models.Index(fields=['eh_interno_grupo', 'data_competencia'], name='lancamento__eh_inte_e339d6_idx'), models.Index(fields=['grupo_ref'], name='lancamento__grupo_r_d3417f_idx'), models.Index(fields=['empresa', 'loja', 'data_competencia'], name='lancamento__empresa_c1a545_idx')],
            },
        ),
    ]
