# Generated by Django 6.0.3 on 2026-03-18 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=150, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='IntegracaoERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_erp', models.CharField(choices=[('venda_erp', 'Venda ERP'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de ERP')),
                ('url_base', models.URLField(blank=True, verbose_name='URL base')),
                ('token', models.TextField(blank=True, verbose_name='Token')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes', to='base.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Integração ERP',
                'verbose_name_plural': 'Integrações ERP',
                'ordering': ['empresa__nome_fantasia', 'tipo_erp'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da loja')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='base.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_codigo_loja_por_empresa')],
            },
        ),
    ]
