# Generated by Django 6.0.3 on 2026-03-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoerp',
            name='pedido_deposito_label',
            field=models.CharField(blank=True, help_text="Campo 'deposito' do orçamento.", max_length=200, verbose_name='Nome depósito (pedido ERP)'),
        ),
        migrations.AddField(
            model_name='integracaoerp',
            name='pedido_empresa_label',
            field=models.CharField(blank=True, help_text="Campo 'empresa' do orçamento. Ex.: nome fantasia na nota.", max_length=200, verbose_name='Nome empresa (pedido ERP)'),
        ),
        migrations.AddField(
            model_name='integracaoerp',
            name='pedido_vendedor_label',
            field=models.CharField(blank=True, help_text="Campo 'vendedor' do orçamento.", max_length=200, verbose_name='Nome vendedor (pedido ERP)'),
        ),
    ]
