# Generated by Django 6.0.3 on 2026-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_align_empresa_nome_fantasia_mongo'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoerp',
            name='pedido_status_sistema',
            field=models.CharField(blank=True, help_text='Campo statusSistema em Pedidos/Salvar. Vazio = usa VENDA_ERP_PEDIDO_STATUS_SISTEMA (settings/.env).', max_length=80, verbose_name='Status sistema (pedido ERP)'),
        ),
    ]
