# Generated by Django 6.0.3 on 2026-04-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_integracao_pedido_status_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoerp',
            name='pedido_plano_conta',
            field=models.CharField(blank=True, help_text='Texto do plano em Pedidos/Salvar (ex.: 1.1.3 — Vendas Sisvale). Vazio = usa VENDA_ERP_PEDIDO_PLANO_CONTA (settings/.env).', max_length=300, verbose_name='Plano de contas (pedido ERP)'),
        ),
    ]
