# Generated by Django 6.0.3 on 2026-04-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_integracao_pedido_plano_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaoerp',
            name='pedido_plano_conta_id',
            field=models.CharField(blank=True, help_text='PlanoDeContaID no Mongo (string). Vazio = tenta resolver pelo texto em DtoLancamento ou usa VENDA_ERP_PEDIDO_PLANO_CONTA_ID.', max_length=32, verbose_name='ID plano de contas (pedido ERP)'),
        ),
    ]
