# Generated by Django 6.0.3 on 2026-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_integracao_pedido_plano_conta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoerp',
            name='pedido_plano_conta',
            field=models.CharField(blank=True, help_text='Texto do plano em Pedidos/Salvar (ex.: 1.1.3 — Vendas SisVale). Vazio = usa VENDA_ERP_PEDIDO_PLANO_CONTA (settings/.env).', max_length=300, verbose_name='Plano de contas (pedido ERP)'),
        ),
    ]
