# Generated by Django 6.0.3 on 2026-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_limpar_plano_pedido_erp_sisvale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaoerp',
            name='pedido_plano_conta',
            field=models.CharField(blank=True, help_text='Texto do plano em Pedidos/Salvar (ex.: Vendas Pdv ou 1.1.1 — Vendas Pdv). Vazio = usa VENDA_ERP_PEDIDO_PLANO_CONTA (settings/.env).', max_length=300, verbose_name='Plano de contas (pedido ERP)'),
        ),
    ]
